/**
 * Combined Verification Config - L1 + L2 Data
 * Complete verification structure combining customer onboarding and loan details
 */

export const combinedVerificationConfig = {
  customers: {
    IL_HD_AH_305: {
      customer: {
        name: "Arjun Patel",
        mifixId: "IL_HD_AH_305",
        product: "L1 Customer Onboarding + HDFC RBGFF KCC",
        overallStatus: "pending",
        verificationProgress: {
          total: 85,
          completed: 61,
          pending: 24,
        },
      },
      documentImages: [
        {
          id: "kyc_photo",
          label: "KYC Photo",
          url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
          status: "verified",
          confidence: 98,
        },
        {
          id: "aadhaar_front",
          label: "Aadhaar Front",
          url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400",
          status: "verified",
          confidence: 96,
        },
        {
          id: "aadhaar_back",
          label: "Aadhaar Back",
          url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=400",
          status: "verified",
          confidence: 94,
        },
        {
          id: "pan_card",
          label: "PAN Card",
          url: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400",
          status: "verified",
          confidence: 92,
        },
        {
          id: "land_photo_1",
          label: "Land Photo 1",
          url: "https://darwin-upload.s3.ap-south-1.amazonaws.com/e32f6e8f-e7f0-4579-bfb3-1646b4dacdc3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA5VRWN4DOCNI7EG5P%2F20251111%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20251111T090449Z&X-Amz-Expires=86400&X-Amz-Signature=0b48133b8530a401e3dad088e9bdc6c174f23f70949c83a01ff6f29cb8b53f2d&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject",
          status: "verified",
          confidence: 98,
        },
        {
          id: "land_photo_2",
          label: "Land Photo 2",
          url: "https://darwin-upload.s3.ap-south-1.amazonaws.com/4c47f1e6-2d36-4df0-943c-9372ae2c470a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA5VRWN4DOCNI7EG5P%2F20251111%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20251111T103144Z&X-Amz-Expires=86400&X-Amz-Signature=79375b816d848fbb3ecf561bcb2311ba93e73e336a3890b2dcd2af986ddc94c2&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject",
          status: "verified",
          confidence: 96,
        },
        {
          id: "patta_document",
          label: "Patta/Chitta/Adangal",
          url: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=400",
          status: "verified",
          confidence: 92,
        },
        {
          id: "crop_photo",
          label: "Crop/Cultivation Photo",
          url: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400",
          status: "verified",
          confidence: 95,
        },
      ],
      sections: [
        // L1 Customer Onboarding Sections
        {
          id: "applicant_details",
          title: "Applicant Details",
          subtitle: "Personal information verification",
          icon: "Person",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "full_name",
              label: "Full Name",
              value: "Arjun Patel",
              status: "verified",
              type: "text",
            },
            {
              id: "date_of_birth",
              label: "Date of Birth",
              value: "15/06/1985",
              status: "verified",
              type: "text",
              subValue: "38 years old",
            },
            {
              id: "age",
              label: "Age",
              value: "38",
              status: "verified",
              type: "number",
            },
            {
              id: "gender",
              label: "Gender",
              value: "Male",
              status: "verified",
              type: "text",
            },
            {
              id: "father_name",
              label: "Father's Name",
              value: "Mohan Patel",
              status: "pending",
              type: "text",
              flagged: true,
              reason: "Name verification pending with documents",
            },
            {
              id: "mother_name",
              label: "Mother's Name",
              value: "Lakshmi Devi",
              status: "verified",
              type: "text",
            },
            {
              id: "marital_status",
              label: "Marital Status",
              value: "Married",
              status: "verified",
              type: "text",
            },
            {
              id: "education",
              label: "Education",
              value: "Graduate",
              status: "verified",
              type: "text",
            },
            {
              id: "mobile_number",
              label: "Mobile Number",
              value: "+91 98765 12345",
              status: "verified",
              type: "text",
            },
            {
              id: "pan_number",
              label: "PAN Number",
              value: "ABCDE1234F",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "kyc_address",
          title: "KYC Address",
          subtitle: "Address as per KYC documents",
          icon: "Home",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "house_number",
              label: "House Number",
              value: "12-A",
              status: "verified",
              type: "text",
            },
            {
              id: "street",
              label: "Street",
              value: "MG Road",
              status: "verified",
              type: "text",
            },
            {
              id: "locality",
              label: "Locality",
              value: "Gandhi Nagar",
              status: "verified",
              type: "text",
            },
            {
              id: "state",
              label: "State",
              value: "Karnataka",
              status: "verified",
              type: "text",
            },
            {
              id: "pin_code",
              label: "PIN Code",
              value: "560001",
              status: "pending",
              type: "text",
              flagged: true,
              reason: "PIN code mismatch with utility bills",
            },
            {
              id: "district",
              label: "District",
              value: "Bangalore Urban",
              status: "pending",
              type: "text",
            },
          ],
        },
        {
          id: "current_address",
          title: "Current Address",
          subtitle: "Present residential address",
          icon: "Home",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "same_as_kyc",
              label: "Same as KYC Address",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "house_number",
              label: "House Number",
              value: "12-A",
              status: "verified",
              type: "text",
            },
            {
              id: "street",
              label: "Street",
              value: "MG Road",
              status: "verified",
              type: "text",
            },
            {
              id: "locality",
              label: "Locality",
              value: "Gandhi Nagar",
              status: "verified",
              type: "text",
            },
            {
              id: "pin_code",
              label: "PIN Code",
              value: "560001",
              status: "verified",
              type: "text",
            },
            {
              id: "alternate_mobile",
              label: "Alternate Mobile",
              value: "+91 98765 43211",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "bank_details",
          title: "Bank Details",
          subtitle: "Banking information",
          icon: "AccountBalance",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "bank_state",
              label: "Bank State",
              value: "Karnataka",
              status: "verified",
              type: "text",
            },
            {
              id: "bank_city",
              label: "Bank City",
              value: "Bangalore",
              status: "verified",
              type: "text",
            },
            {
              id: "sol_id",
              label: "SOL ID",
              value: "HDFC0001234",
              status: "verified",
              type: "text",
            },
            {
              id: "annual_income",
              label: "Annual Income",
              value: "₹5,00,000",
              status: "pending",
              type: "currency",
              flagged: true,
              reason: "Income verification documents pending",
            },
          ],
        },
        {
          id: "kyc_documents",
          title: "KYC Documents",
          subtitle: "Identity verification details",
          icon: "Description",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "kyc_type",
              label: "KYC Type",
              value: "Aadhaar",
              status: "verified",
              type: "text",
            },
            {
              id: "aadhaar_number",
              label: "Aadhaar Number",
              value: "XXXX XXXX 9012",
              status: "verified",
              type: "text",
            },
            {
              id: "issue_date",
              label: "Issue Date",
              value: "15/01/2020",
              status: "verified",
              type: "text",
            },
            {
              id: "expiry_date",
              label: "Expiry Date",
              value: "15/01/2030",
              status: "verified",
              type: "text",
            },
            {
              id: "category",
              label: "Category",
              value: "General",
              status: "verified",
              type: "text",
            },
          ],
        },
        
        // L2 Instant KCC Sections
        {
          id: "land_details",
          title: "Land Details",
          subtitle: "Property and land ownership information",
          icon: "Home",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "allied_loan",
              label: "Allied Loan Type",
              value: "Poultry",
              status: "verified",
              type: "text",
            },
            {
              id: "state_land",
              label: "State",
              value: "Karnataka",
              status: "verified",
              type: "text",
            },
            {
              id: "district_land",
              label: "District",
              value: "Bangalore Urban",
              status: "verified",
              type: "text",
            },
            {
              id: "taluk",
              label: "Taluk",
              value: "Bangalore North",
              status: "verified",
              type: "text",
            },
            {
              id: "village",
              label: "Village",
              value: "Yelahanka",
              status: "verified",
              type: "text",
            },
            {
              id: "survey_number",
              label: "Survey Number",
              value: "SV-123/456",
              status: "verified",
              type: "text",
            },
            {
              id: "sub_division_number",
              label: "Sub Division Number",
              value: "SD-01",
              status: "verified",
              type: "text",
            },
            {
              id: "land_owner_name",
              label: "Land Owner Name",
              value: "Rajesh Kumar",
              status: "pending",
              type: "text",
              flagged: true,
              reason: "Name mismatch - verify with documents",
            },
            {
              id: "land_extent",
              label: "Land Extent (Acres)",
              value: "2.5",
              status: "verified",
              type: "number",
            },
            {
              id: "patta_no",
              label: "Patta Number",
              value: "PT-12345",
              status: "verified",
              type: "text",
            },
            {
              id: "land_record_verified",
              label: "Land Record Status",
              value: "Verified",
              status: "verified",
              type: "text",
            },
            {
              id: "document_type",
              label: "Document Type",
              value: "Patta/Chitta/Adangal",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "land_classification",
          title: "Land Classification & Usage",
          subtitle: "Land type and cultivation details",
          icon: "Business",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "land_classification",
              label: "Land Classification",
              value: "Irrigated",
              status: "verified",
              type: "text",
            },
            {
              id: "joint_patta",
              label: "Joint Patta",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "cultivable_land",
              label: "Cultivable Land (Acres)",
              value: "2.3",
              status: "verified",
              type: "number",
            },
            {
              id: "land_holding",
              label: "Total Land Holding (Acres)",
              value: "2.5",
              status: "verified",
              type: "number",
            },
            {
              id: "land_holding_by_applicant",
              label: "Land Holding by Applicant (Acres)",
              value: "2.5",
              status: "verified",
              type: "number",
            },
            {
              id: "irrigation_electricity",
              label: "Irrigation & Electricity",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "land_proof_submitted",
              label: "Land Proof Submitted",
              value: "Yes",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "crop_details",
          title: "Crop & Cultivation Details",
          subtitle: "Agricultural crop and season information",
          icon: "Description",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "crop_group",
              label: "Crop Group",
              value: "Cereals",
              status: "verified",
              type: "text",
            },
            {
              id: "crop_name",
              label: "Crop Name",
              value: "Paddy",
              status: "verified",
              type: "text",
            },
            {
              id: "season",
              label: "Season",
              value: "Kharif",
              status: "verified",
              type: "text",
            },
            {
              id: "scale_of_finance",
              label: "Scale of Finance (₹)",
              value: "₹45,000",
              status: "verified",
              type: "currency",
            },
            {
              id: "applicant_farming",
              label: "Applicant Actively Farming",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "family_farming",
              label: "Family Involved in Farming",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "farming_experience",
              label: "Farming Experience (Years)",
              value: "15 years",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "livestock_details",
          title: "Livestock Details",
          subtitle: "Animal husbandry and dairy information",
          icon: "AccountBalance",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "animal_type",
              label: "Animal Type",
              value: "Buffaloes",
              status: "verified",
              type: "text",
            },
            {
              id: "breed",
              label: "Breed",
              value: "Murrah",
              status: "verified",
              type: "text",
            },
            {
              id: "number_of_animals",
              label: "Number of Animals",
              value: "8",
              status: "verified",
              type: "number",
            },
            {
              id: "milk_society_name",
              label: "Milk Society Name",
              value: "Ahope",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "loan_details_kcc",
          title: "Loan Details",
          subtitle: "Financial and loan information",
          icon: "AccountBalance",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "eligible_loan_amount",
              label: "Eligible Loan Amount",
              value: "₹1,12,500",
              status: "verified",
              type: "currency",
            },
            {
              id: "opted_loan_amount",
              label: "Opted Loan Amount",
              value: "₹1,00,000",
              status: "verified",
              type: "currency",
            },
            {
              id: "scheme_type",
              label: "Scheme Type",
              value: "Kisan Credit Card",
              status: "verified",
              type: "text",
            },
            {
              id: "loan_tenor",
              label: "Loan Tenor",
              value: "12 Months",
              status: "verified",
              type: "text",
            },
            {
              id: "security_value",
              label: "Security Value",
              value: "₹1,12,500",
              status: "verified",
              type: "currency",
            },
            {
              id: "opt_pmfby",
              label: "Opted for PMFBY Insurance",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "prospect_consent",
              label: "Prospect Consent",
              value: "Given",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "verification_details",
          title: "Field Verification Details",
          subtitle: "On-ground verification and assessment",
          icon: "Description",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "distance_from_branch",
              label: "Distance from Branch (km)",
              value: "5.5 km",
              status: "verified",
              type: "text",
            },
            {
              id: "market_availability",
              label: "Market Availability (km)",
              value: "3.2 km",
              status: "verified",
              type: "text",
            },
            {
              id: "able_to_carry",
              label: "Able to Carry Out Business",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "agri_officer_comments",
              label: "Agriculture Officer Comments",
              value: "Good land condition with proper irrigation facilities",
              status: "verified",
              type: "longtext",
            },
          ],
        },
      ],
    },
  },
};

export default combinedVerificationConfig;
