/**
 * L1 Customer Verification Configuration
 * Enhanced verification checklist with images and data points for web-based validation
 */

export const l1VerificationConfig = {
  // Mock image URLs for different document types
  mockImages: {
    customerPhotos: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    ],
    addressProofs: [
      "https://images.unsplash.com/photo-1554224311-beee1c7c3c39?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&h=300&fit=crop",
    ],
    kycDocuments: [
      "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1434626881859-194d67b2b86f?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=300&fit=crop",
    ],
  },

  // Enhanced customer verification data
  customers: {
    IL_HD_AH_305: {
      customer: {
        name: "Arjun Patel",
        mifixId: "IL_HD_AH_305",
        product: "L1 Customer Onboarding",
        amount: "₹5,00,000",
        overallStatus: "pending",
        verificationProgress: {
          completed: 23,
          total: 35,
          percentage: 66,
        },
      },
      // Document images for Customer View panel
      documentImages: [
        {
          id: "prospect_photo_kyc",
          label: "KYC Photo",
          url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
          status: "verified",
          confidence: 95,
          type: "customer_photo",
        },
        {
          id: "prospect_recent_photo",
          label: "Recent Photo",
          url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
          status: "verified",
          confidence: 92,
          type: "customer_photo",
        },
        {
          id: "aadhaar_front",
          label: "Aadhaar Front",
          url: "https://images.unsplash.com/photo-1554224311-beee1c7c3c39?w=400&h=300&fit=crop",
          status: "verified",
          confidence: 88,
          type: "kyc_document",
        },
        {
          id: "aadhaar_back",
          label: "Aadhaar Back",
          url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=300&fit=crop",
          status: "verified",
          confidence: 90,
          type: "kyc_document",
        },
        {
          id: "pan_card",
          label: "PAN Card",
          url: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=400&h=300&fit=crop",
          status: "pending",
          confidence: 78,
          flagged: true,
          reason: "Image quality below standard",
          type: "kyc_document",
        },
        {
          id: "address_proof_1",
          label: "Address Proof",
          url: "https://images.unsplash.com/photo-1434626881859-194d67b2b86f?w=400&h=300&fit=crop",
          status: "verified",
          confidence: 85,
          type: "address_proof",
        },
        {
          id: "signature_sample",
          label: "Signature",
          url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&h=300&fit=crop",
          status: "pending",
          confidence: 82,
          type: "signature",
        },
      ],
      sections: [
        {
          id: "applicant_details",
          title: "Applicant Details",
          subtitle: "Personal information verification",
          icon: "Person",
          type: "data",
          progress: { completed: 8, total: 10 },
          fields: [
            {
              id: "full_name",
              label: "Full Name",
              value: "Arjun Patel",
              expectedValue: "Arjun Patel",
              status: "verified",
              confidence: 98,
            },
            {
              id: "date_of_birth",
              label: "Date of Birth",
              value: "15/06/1985",
              expectedValue: "15/06/1985",
              status: "verified",
              confidence: 100,
              subValue: "38 years old",
            },
            {
              id: "age",
              label: "Age",
              value: "38",
              expectedValue: "38",
              status: "verified",
              confidence: 100,
            },
            {
              id: "gender",
              label: "Gender",
              value: "Male",
              expectedValue: "Male",
              status: "verified",
              confidence: 100,
            },
            {
              id: "father_name",
              label: "Father's Name",
              value: "Mohan Patel",
              expectedValue: "Mohan Kumar",
              status: "pending",
              confidence: 75,
              flagged: true,
              reason: "Name mismatch detected",
            },
            {
              id: "mother_name",
              label: "Mother's Name",
              value: "Lakshmi Devi",
              expectedValue: "Lakshmi Devi",
              status: "verified",
              confidence: 100,
            },
            {
              id: "marital_status",
              label: "Marital Status",
              value: "Married",
              expectedValue: "Married",
              status: "verified",
              confidence: 100,
            },
            {
              id: "educational_qualification",
              label: "Education",
              value: "Graduate",
              expectedValue: "Graduate",
              status: "verified",
              confidence: 100,
            },
            {
              id: "mobile_number",
              label: "Mobile Number",
              value: "+91 98765 12345",
              expectedValue: "+91 98765 12345",
              status: "verified",
              confidence: 100,
            },
            {
              id: "pan_number",
              label: "PAN Number",
              value: "ABCDE1234F",
              expectedValue: "ABCDE1234F",
              status: "pending",
              confidence: 85,
              reason: "Requires manual verification",
            },
          ],
        },
        {
          id: "kyc_address",
          title: "KYC Address",
          subtitle: "Address as per KYC documents",
          icon: "Home",
          type: "data",
          progress: { completed: 4, total: 6 },
          fields: [
            {
              id: "kyc_house_number",
              label: "House Number",
              value: "12-A",
              expectedValue: "12-A",
              status: "verified",
              confidence: 100,
            },
            {
              id: "kyc_street",
              label: "Street",
              value: "MG Road",
              expectedValue: "MG Road",
              status: "verified",
              confidence: 100,
            },
            {
              id: "kyc_locality",
              label: "Locality",
              value: "Gandhi Nagar",
              expectedValue: "Gandhi Nagar",
              status: "verified",
              confidence: 100,
            },
            {
              id: "kyc_state",
              label: "State",
              value: "Karnataka",
              expectedValue: "Karnataka",
              status: "verified",
              confidence: 100,
            },
            {
              id: "kyc_pin_code",
              label: "Pin Code",
              value: "560001",
              expectedValue: "560001",
              status: "pending",
              confidence: 90,
              reason: "OCR confidence below threshold",
            },
            {
              id: "kyc_district",
              label: "District",
              value: "Bangalore Urban",
              expectedValue: "Bangalore Urban",
              status: "pending",
              confidence: 88,
            },
          ],
        },
        {
          id: "current_address",
          title: "Current Address",
          subtitle: "Present residential address",
          icon: "Home",
          type: "data",
          progress: { completed: 5, total: 6 },
          allowComments: true,
          fields: [
            {
              id: "same_as_kyc",
              label: "Same as KYC Address",
              value: "Yes",
              expectedValue: "Yes",
              status: "verified",
              confidence: 100,
            },
            {
              id: "current_house_number",
              label: "House Number",
              value: "12-A",
              expectedValue: "12-A",
              status: "verified",
              confidence: 100,
            },
            {
              id: "current_street",
              label: "Street",
              value: "MG Road",
              expectedValue: "MG Road",
              status: "verified",
              confidence: 100,
            },
            {
              id: "current_locality",
              label: "Locality",
              value: "Gandhi Nagar",
              expectedValue: "Gandhi Nagar",
              status: "verified",
              confidence: 100,
            },
            {
              id: "current_pin_code",
              label: "Pin Code",
              value: "560001",
              expectedValue: "560001",
              status: "verified",
              confidence: 95,
            },
            {
              id: "alternate_mobile",
              label: "Alternate Mobile",
              value: "+91 98765 43211",
              expectedValue: "+91 98765 43211",
              status: "pending",
              confidence: 88,
            },
          ],
        },
        {
          id: "bank_details",
          title: "Bank Details",
          subtitle: "Banking information",
          icon: "AccountBalance",
          type: "data",
          progress: { completed: 3, total: 4 },
          allowComments: true,
          fields: [
            {
              id: "bank_state",
              label: "Bank State",
              value: "Karnataka",
              expectedValue: "Karnataka",
              status: "verified",
              confidence: 100,
            },
            {
              id: "bank_city",
              label: "Bank City",
              value: "Bangalore",
              expectedValue: "Bangalore",
              status: "verified",
              confidence: 100,
            },
            {
              id: "sol_id",
              label: "SOL ID",
              value: "HDFC0001234",
              expectedValue: "HDFC0001234",
              status: "verified",
              confidence: 100,
            },
            {
              id: "annual_income",
              label: "Annual Income",
              value: "₹5,00,000",
              expectedValue: "₹5,00,000",
              status: "pending",
              confidence: 85,
            },
          ],
        },
        {
          id: "kyc_documents",
          title: "KYC Documents",
          subtitle: "Identity verification details",
          icon: "Description",
          type: "data",
          progress: { completed: 4, total: 5 },
          allowComments: true,
          fields: [
            {
              id: "kyc_type",
              label: "KYC Type",
              value: "Aadhaar",
              expectedValue: "Aadhaar",
              status: "verified",
              confidence: 100,
            },
            {
              id: "kyc_number",
              label: "Aadhaar Number",
              value: "XXXX XXXX 9012",
              expectedValue: "XXXX XXXX 9012",
              status: "verified",
              confidence: 95,
            },
            {
              id: "id_issue_date",
              label: "Issue Date",
              value: "15/01/2020",
              expectedValue: "15/01/2020",
              status: "verified",
              confidence: 92,
            },
            {
              id: "id_expiry_date",
              label: "Expiry Date",
              value: "15/01/2030",
              expectedValue: "15/01/2030",
              status: "verified",
              confidence: 92,
            },
            {
              id: "belongs_to",
              label: "Category",
              value: "General",
              expectedValue: "General",
              status: "pending",
              confidence: 80,
            },
          ],
        },
      ],
    },
    JL_HD_JP_507: {
      customer: {
        name: "Devanshi Mehta",
        mifixId: "JL_HD_JP_507",
        product: "L1 Customer Onboarding",
        amount: "₹7,50,000",
        overallStatus: "pending",
        verificationProgress: {
          completed: 15,
          total: 18,
          percentage: 83,
        },
      },
      sections: [
        {
          id: "applicant_details",
          title: "Applicant Details",
          subtitle: "Personal information verification",
          icon: "Person",
          type: "data",
          progress: { completed: 9, total: 10 },
          fields: [
            {
              id: "full_name",
              label: "Full Name",
              value: "Devanshi Mehta",
              expectedValue: "Devanshi Mehta",
              status: "verified",
              confidence: 100,
            },
            {
              id: "date_of_birth",
              label: "Date of Birth",
              value: "15/08/1985",
              expectedValue: "15/08/1985",
              status: "verified",
              confidence: 100,
              subValue: "38 years old",
            },
            {
              id: "gender",
              label: "Gender",
              value: "Female",
              expectedValue: "Female",
              status: "verified",
              confidence: 100,
            },
            {
              id: "father_name",
              label: "Father's Name",
              value: "Rajesh Mehta",
              expectedValue: "Rajesh Mehta",
              status: "verified",
              confidence: 100,
            },
            {
              id: "mobile_number",
              label: "Mobile Number",
              value: "+91 98765 43210",
              expectedValue: "+91 98765 43210",
              status: "verified",
              confidence: 100,
            },
            {
              id: "pan_number",
              label: "PAN Number",
              value: "ABCDE1234F",
              expectedValue: "ABCDE1234F",
              status: "verified",
              confidence: 95,
            },
          ],
        },
        {
          id: "document_images",
          title: "Document Images",
          subtitle: "Uploaded documents and photos",
          icon: "Description",
          type: "images",
          progress: { completed: 6, total: 8 },
          imageGrid: {
            columns: 3,
            allowComparison: true,
          },
          fields: [
            {
              id: "prospect_photo_kyc",
              label: "KYC Photo",
              url: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face",
              status: "verified",
              confidence: 98,
            },
            {
              id: "prospect_recent_photo",
              label: "Recent Photo",
              url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
              status: "verified",
              confidence: 96,
            },
            {
              id: "aadhaar_front",
              label: "Aadhaar Front",
              url: "https://images.unsplash.com/photo-1554224311-beee1c7c3c39?w=400&h=300&fit=crop",
              status: "verified",
              confidence: 92,
            },
          ],
        },
      ],
    },
    JL_HD_CH_912: {
      customer: {
        name: "Rajesh Kumar",
        mifixId: "JL_HD_CH_912",
        product: "L1 Customer Onboarding",
        amount: "₹9,20,000",
        overallStatus: "pending",
        verificationProgress: {
          completed: 10,
          total: 18,
          percentage: 56,
        },
      },
      sections: [
        {
          id: "applicant_details",
          title: "Applicant Details",
          subtitle: "Personal information verification",
          icon: "Person",
          type: "data",
          progress: { completed: 6, total: 10 },
          fields: [
            {
              id: "full_name",
              label: "Full Name",
              value: "Rajesh Kumar",
              expectedValue: "Rajesh Kumar",
              status: "verified",
              confidence: 100,
            },
            {
              id: "mobile_number",
              label: "Mobile Number",
              value: "+91 98781 23456",
              expectedValue: "+91 98781 23456",
              status: "verified",
              confidence: 100,
            },
            {
              id: "pan_number",
              label: "PAN Number",
              value: "FGHIJ5678K",
              expectedValue: "FGHIJ5678K",
              status: "pending",
              confidence: 65,
              flagged: true,
              reason: "Low OCR confidence, manual review required",
            },
          ],
        },
        {
          id: "document_images",
          title: "Document Images",
          subtitle: "Uploaded documents and photos",
          icon: "Description",
          type: "images",
          progress: { completed: 4, total: 8 },
          imageGrid: {
            columns: 3,
            allowComparison: true,
          },
          fields: [
            {
              id: "prospect_photo_kyc",
              label: "KYC Photo",
              url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
              status: "verified",
              confidence: 94,
            },
            {
              id: "aadhaar_front",
              label: "Aadhaar Front",
              url: "https://images.unsplash.com/photo-1554224311-beee1c7c3c39?w=400&h=300&fit=crop",
              status: "pending",
              confidence: 72,
              reason: "Blurry image, retake recommended",
            },
          ],
        },
      ],
    },
  },

  // Verification rules and thresholds
  verificationRules: {
    confidenceThreshold: 80,
    flaggedThreshold: 75,
    imageQualityThreshold: 85,
    ocrAccuracyThreshold: 90,
  },

  // Image comparison settings
  imageComparison: {
    maxCompareImages: 2,
    supportedComparisons: [
      {
        type: "face_match",
        fields: ["prospect_photo_kyc", "prospect_recent_photo"],
      },
      {
        type: "document_verification",
        fields: ["aadhaar_front", "aadhaar_back"],
      },
      {
        type: "address_verification",
        fields: ["address_proof_1", "address_proof_2"],
      },
    ],
  },
};

export default l1VerificationConfig;
