/**
 * L2 Verification Config - Instant KCC (Land & Crop Details)
 * Complete verification structure for HDFC RBGFF land and agriculture loans
 */

export const l2VerificationConfig = {
  customers: {
    IL_HD_AH_305: {
      customer: {
        name: "Arjun Patel",
        mifixId: "IL_HD_AH_305",
        product: "L1 Customer Onboarding + HDFC RBGFF KCC",
        overallStatus: "pending",
        verificationProgress: {
          total: 85,
          completed: 61,
          pending: 24,
        },
      },
      documentImages: [
        {
          id: "land_photo_1",
          label: "Land Photo 1",
          url: "https://darwin-upload.s3.ap-south-1.amazonaws.com/e32f6e8f-e7f0-4579-bfb3-1646b4dacdc3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA5VRWN4DOCNI7EG5P%2F20251111%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20251111T090449Z&X-Amz-Expires=86400&X-Amz-Signature=0b48133b8530a401e3dad088e9bdc6c174f23f70949c83a01ff6f29cb8b53f2d&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject",
          status: "verified",
          confidence: 98,
        },
        {
          id: "land_photo_2",
          label: "Land Photo 2",
          url: "https://darwin-upload.s3.ap-south-1.amazonaws.com/4c47f1e6-2d36-4df0-943c-9372ae2c470a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA5VRWN4DOCNI7EG5P%2F20251111%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20251111T103144Z&X-Amz-Expires=86400&X-Amz-Signature=79375b816d848fbb3ecf561bcb2311ba93e73e336a3890b2dcd2af986ddc94c2&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject",
          status: "verified",
          confidence: 96,
        },
        {
          id: "land_document",
          label: "Land Ownership Document",
          url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400",
          status: "verified",
          confidence: 94,
        },
        {
          id: "patta_document",
          label: "Patta/Chitta/Adangal",
          url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=400",
          status: "verified",
          confidence: 92,
        },
        {
          id: "survey_map",
          label: "Survey Map",
          url: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=400",
          status: "pending",
          confidence: 88,
        },
        {
          id: "crop_photo",
          label: "Crop/Cultivation Photo",
          url: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400",
          status: "verified",
          confidence: 95,
        },
        {
          id: "irrigation_proof",
          label: "Irrigation Facility Photo",
          url: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400",
          status: "verified",
          confidence: 90,
        },
      ],
      sections: [
        {
          id: "land_details",
          title: "Land Details",
          subtitle: "Property and land ownership information",
          icon: "Home",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "allied_loan",
              label: "Allied Loan Type",
              value: "Poultry",
              status: "verified",
              type: "text",
            },
            {
              id: "state",
              label: "State",
              value: "Karnataka",
              status: "verified",
              type: "text",
            },
            {
              id: "district",
              label: "District",
              value: "Bangalore Urban",
              status: "verified",
              type: "text",
            },
            {
              id: "taluk",
              label: "Taluk",
              value: "Bangalore North",
              status: "verified",
              type: "text",
            },
            {
              id: "village",
              label: "Village",
              value: "Yelahanka",
              status: "verified",
              type: "text",
            },
            {
              id: "survey_number",
              label: "Survey Number",
              value: "SV-123/456",
              status: "verified",
              type: "text",
            },
            {
              id: "sub_division_number",
              label: "Sub Division Number",
              value: "SD-01",
              status: "verified",
              type: "text",
            },
            {
              id: "land_owner_name",
              label: "Land Owner Name",
              value: "Rajesh Kumar",
              status: "pending",
              type: "text",
              flagged: true,
              reason: "Name mismatch - verify with documents",
            },
            {
              id: "land_extent",
              label: "Land Extent (Acres)",
              value: "2.5",
              status: "verified",
              type: "number",
            },
            {
              id: "patta_no",
              label: "Patta Number",
              value: "PT-12345",
              status: "verified",
              type: "text",
            },
            {
              id: "land_record_verified",
              label: "Land Record Status",
              value: "Verified",
              status: "verified",
              type: "text",
            },
            {
              id: "document_type",
              label: "Document Type",
              value: "Patta/Chitta/Adangal",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "land_classification",
          title: "Land Classification & Usage",
          subtitle: "Land type and cultivation details",
          icon: "Business",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "land_classification",
              label: "Land Classification",
              value: "Irrigated",
              status: "verified",
              type: "text",
            },
            {
              id: "joint_patta",
              label: "Joint Patta",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "cultivable_land",
              label: "Cultivable Land (Acres)",
              value: "2.3",
              status: "verified",
              type: "number",
            },
            {
              id: "land_holding",
              label: "Total Land Holding (Acres)",
              value: "2.5",
              status: "verified",
              type: "number",
            },
            {
              id: "land_holding_by_applicant",
              label: "Land Holding by Applicant (Acres)",
              value: "2.5",
              status: "verified",
              type: "number",
            },
            {
              id: "irrigation_electricity",
              label: "Irrigation & Electricity",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "land_proof_submitted",
              label: "Land Proof Submitted",
              value: "Yes",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "crop_details",
          title: "Crop & Cultivation Details",
          subtitle: "Agricultural crop and season information",
          icon: "Description",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "crop_group",
              label: "Crop Group",
              value: "Cereals",
              status: "verified",
              type: "text",
            },
            {
              id: "crop_name",
              label: "Crop Name",
              value: "Paddy",
              status: "verified",
              type: "text",
            },
            {
              id: "season",
              label: "Season",
              value: "Kharif",
              status: "verified",
              type: "text",
            },
            {
              id: "scale_of_finance",
              label: "Scale of Finance (₹)",
              value: "₹45,000",
              status: "verified",
              type: "currency",
            },
            {
              id: "applicant_farming",
              label: "Applicant Actively Farming",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "family_farming",
              label: "Family Involved in Farming",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "farming_experience",
              label: "Farming Experience (Years)",
              value: "15 years",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "livestock_details",
          title: "Livestock Details",
          subtitle: "Animal husbandry and dairy information",
          icon: "AccountBalance",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "animal_type",
              label: "Animal Type",
              value: "Buffaloes",
              status: "verified",
              type: "text",
            },
            {
              id: "breed",
              label: "Breed",
              value: "Murrah",
              status: "verified",
              type: "text",
            },
            {
              id: "number_of_animals",
              label: "Number of Animals",
              value: "8",
              status: "verified",
              type: "number",
            },
            {
              id: "milk_society_name",
              label: "Milk Society Name",
              value: "Ahope",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "loan_details",
          title: "Loan Details",
          subtitle: "Financial and loan information",
          icon: "AccountBalance",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "eligible_loan_amount",
              label: "Eligible Loan Amount",
              value: "₹1,12,500",
              status: "verified",
              type: "currency",
            },
            {
              id: "opted_loan_amount",
              label: "Opted Loan Amount",
              value: "₹1,00,000",
              status: "verified",
              type: "currency",
            },
            {
              id: "scheme_type",
              label: "Scheme Type",
              value: "Kisan Credit Card",
              status: "verified",
              type: "text",
            },
            {
              id: "loan_tenor",
              label: "Loan Tenor",
              value: "12 Months",
              status: "verified",
              type: "text",
            },
            {
              id: "security_value",
              label: "Security Value",
              value: "₹1,12,500",
              status: "verified",
              type: "currency",
            },
            {
              id: "opt_pmfby",
              label: "Opted for PMFBY Insurance",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "prospect_consent",
              label: "Prospect Consent",
              value: "Given",
              status: "verified",
              type: "text",
            },
          ],
        },
        {
          id: "verification_details",
          title: "Field Verification Details",
          subtitle: "On-ground verification and assessment",
          icon: "Description",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "distance_from_branch",
              label: "Distance from Branch (km)",
              value: "5.5 km",
              status: "verified",
              type: "text",
            },
            {
              id: "market_availability",
              label: "Market Availability (km)",
              value: "3.2 km",
              status: "verified",
              type: "text",
            },
            {
              id: "able_to_carry",
              label: "Able to Carry Out Business",
              value: "Yes",
              status: "verified",
              type: "text",
            },
            {
              id: "agri_officer_comments",
              label: "Agriculture Officer Comments",
              value: "Good land condition with proper irrigation facilities",
              status: "verified",
              type: "longtext",
            },
          ],
        },
      ],
    },
    // Additional customers can be added here
    JL_HD_CH_810: {
      customer: {
        name: "Gaganpreet Singh",
        mifixId: "JL_HD_CH_810",
        product: "HDFC RBGFF - Instant KCC",
        overallStatus: "pending",
        verificationProgress: {
          total: 50,
          completed: 35,
          pending: 15,
        },
      },
      documentImages: [
        {
          id: "land_photo_1",
          label: "Land Photo 1",
          url: "https://darwin-upload.s3.ap-south-1.amazonaws.com/e32f6e8f-e7f0-4579-bfb3-1646b4dacdc3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA5VRWN4DOCNI7EG5P%2F20251111%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20251111T090449Z&X-Amz-Expires=86400&X-Amz-Signature=0b48133b8530a401e3dad088e9bdc6c174f23f70949c83a01ff6f29cb8b53f2d&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject",
          status: "verified",
          confidence: 95,
        },
        {
          id: "land_photo_2",
          label: "Land Photo 2",
          url: "https://darwin-upload.s3.ap-south-1.amazonaws.com/4c47f1e6-2d36-4df0-943c-9372ae2c470a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA5VRWN4DOCNI7EG5P%2F20251111%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20251111T103144Z&X-Amz-Expires=86400&X-Amz-Signature=79375b816d848fbb3ecf561bcb2311ba93e73e336a3890b2dcd2af986ddc94c2&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject",
          status: "verified",
          confidence: 93,
        },
      ],
      sections: [
        {
          id: "land_details",
          title: "Land Details",
          subtitle: "Property and land ownership information",
          icon: "Home",
          type: "data",
          allowComments: true,
          fields: [
            {
              id: "state",
              label: "State",
              value: "Punjab",
              status: "verified",
              type: "text",
            },
            {
              id: "district",
              label: "District",
              value: "Amritsar",
              status: "verified",
              type: "text",
            },
            // More fields...
          ],
        },
      ],
    },
  },
};

export default l2VerificationConfig;
