// Unified Generic Schema Format
// Supports both form-based and component-based sections

export const LeadsManagementSchema = {
  // Page metadata
  title: "Lead Management",
  description: "Manage and track customer leads",

  // Sections can be either "form" or "component" type
  sections: [
    {
      id: "header_section",
      type: "component", // Component-based section
      componentType: "header",
      title: "Leads Management",
      subtitle: "Manage and track customer leads",
      icon: "list",
      config: {},
    },
    {
      id: "search_section",
      type: "component", // Component-based section
      componentType: "search",
      title: "Search Leads",
      subtitle: "Find prospects quickly",
      icon: "search",
      config: {
        placeholder: "Search by name, address, requirement, or phone...",
        maxWidth: 600,
        startIcon: "Search",
        searchableFields: [
          "name",
          "address",
          "requirement",
          "sourcedBy",
          "mobileNumber",
        ],
        showCount: true,
        countLabel: "prospect",
        emptyMessage: "No prospects found",
        emptyHint: "Try adjusting your search criteria",
      },
    },

    {
      id: "leads_list_section",
      type: "component", // Component-based section
      componentType: "cardList",
      title: "Leads List",
      subtitle: "View all prospects",
      icon: "list",
      config: {
        idKey: "id",
        header: {
          showAvatar: true,
          avatarKey: "name",
          avatarSize: 56,
          titleKey: "name",
          chipKey: "requirement",
          minHeight: "72px",
        },
        fields: [
          {
            id: "address",
            dataKey: "address",
            icon: "LocationOn",
            iconSize: 18,
            fontSize: "0.85rem",
            alignItems: "flex-start",
            minHeight: "38px",
            clamp: 2,
          },
          {
            id: "phone",
            dataKey: "mobileNumber",
            icon: "Phone",
            iconSize: 18,
            fontSize: "0.85rem",
            minHeight: "24px",
          },
          {
            id: "amount",
            dataKey: "amount",
            icon: "AttachMoney",
            iconSize: 18,
            fontSize: "0.85rem",
            fontWeight: 600,
            textColor: "success.main",
            minHeight: "24px",
          },
          {
            id: "sourcedBy",
            dataKey: "sourcedBy",
            icon: "Person",
            iconSize: 18,
            fontSize: "0.85rem",
            prefix: "Sourced by:",
            bold: true,
            minHeight: "24px",
          },
        ],
      },
    },

    {
      id: "lead_details_dialog",
      type: "component", // Component-based section
      componentType: "dialog",
      title: "Lead Details",
      subtitle: "View and edit lead information",
      icon: "person",
      config: {
        maxWidth: "md",
        showAvatar: true,
        avatarKey: "name",
        titleKey: "name",
        subtitle: "Customer Details",
        showEditButton: true,

        // Dialog can have form sections inside
        sections: [
          {
            id: "lead_info_form",
            type: "form", // Form-based section inside dialog
            title: "Lead Information",
            subtitle: "Complete lead details",
            icon: "person",
            fields: [
              {
                id: "name",
                type: "text",
                label: "Full Name",
                dataKey: "name",
                placeholder: "Enter full name",
                required: true,
                icon: "person",
                xs: 12,
                md: 6,
              },
              {
                id: "mobileNumber",
                type: "text",
                label: "Mobile Number",
                dataKey: "mobileNumber",
                placeholder: "Enter mobile number",
                required: true,
                icon: "phone",
                xs: 12,
                md: 6,
                validation: {
                  pattern: "^\\d{10}$",
                  message: "Mobile number must be exactly 10 digits",
                },
              },
              {
                id: "email",
                type: "email",
                label: "Email",
                dataKey: "email",
                placeholder: "Enter email address",
                required: true,
                icon: "email",
                xs: 12,
                md: 6,
                validation: {
                  pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
                  message: "Please enter a valid email address",
                },
              },
              {
                id: "address",
                type: "text",
                label: "Address",
                dataKey: "address",
                placeholder: "Enter address",
                icon: "home",
                xs: 12,
                md: 6,
              },
              {
                id: "requirement",
                type: "select",
                label: "Requirement",
                dataKey: "requirement",
                placeholder: "Select requirement",
                xs: 12,
                md: 6,
                options: [
                  { value: "Home Loan", label: "Home Loan" },
                  { value: "Personal Loan", label: "Personal Loan" },
                  { value: "Business Loan", label: "Business Loan" },
                  { value: "Auto Loan", label: "Auto Loan" },
                ],
              },
              {
                id: "amount",
                type: "text",
                label: "Amount",
                dataKey: "amount",
                placeholder: "Enter amount",
                xs: 12,
                md: 6,
              },
              {
                id: "loanType",
                type: "select",
                label: "Loan Type",
                dataKey: "loanType",
                placeholder: "Select loan type",
                xs: 12,
                md: 6,
                options: [
                  { value: "Home Loan", label: "Home Loan" },
                  { value: "Personal Loan", label: "Personal Loan" },
                  { value: "Business Loan", label: "Business Loan" },
                  { value: "Auto Loan", label: "Auto Loan" },
                ],
              },
              {
                id: "sourcedBy",
                type: "text",
                label: "Sourced By",
                dataKey: "sourcedBy",
                placeholder: "Enter source name",
                icon: "person",
                xs: 12,
                md: 6,
              },
              {
                id: "income",
                type: "text",
                label: "Annual Income",
                dataKey: "income",
                placeholder: "Enter annual income",
                xs: 12,
                md: 4,
              },
              {
                id: "creditScore",
                type: "number",
                label: "Credit Score",
                dataKey: "creditScore",
                placeholder: "Enter credit score",
                xs: 12,
                md: 4,
              },
              {
                id: "employmentStatus",
                type: "select",
                label: "Employment Status",
                dataKey: "employmentStatus",
                placeholder: "Select employment status",
                xs: 12,
                md: 4,
                options: [
                  { value: "Full-time", label: "Full-time" },
                  { value: "Part-time", label: "Part-time" },
                  { value: "Self-employed", label: "Self-employed" },
                  { value: "Unemployed", label: "Unemployed" },
                ],
              },
              {
                id: "notes",
                type: "text",
                label: "Notes",
                dataKey: "notes",
                placeholder: "Enter any additional notes",
                multiline: true,
                rows: 3,
                xs: 12,
              },
            ],
          },
        ],

        // Dialog actions
        actions: [
          {
            id: "accept",
            label: "Accept",
            action: "accept",
            variant: "contained",
            color: "success",
            showIf: "viewing",
          },
          {
            id: "reject",
            label: "Reject",
            action: "reject",
            variant: "contained",
            color: "error",
            showIf: "viewing",
          },

          {
            id: "review",
            label: "Review",
            action: "review",
            variant: "contained",
            color: "warning",
            showIf: "viewing",
          },
          {
            id: "assign_to_rm",
            label: "Assign to RM",
            action: "assign_to_rm",
            variant: "contained",
            color: "warning",
            showIf: "viewing",
          },
        ],
      },
    },
  ],

  // Data source
  data: [
    {
      id: 1,
      name: "John Doe",
      address: "123 Main St, New York, NY 10001",
      requirement: "Home Loan",
      amount: "$250,000",
      sourcedBy: "Sarah Johnson",
      mobileNumber: "7373000632",
      email: "john.doe@email.com",
      loanType: "Home Loan",
      income: "$85,000",
      creditScore: 720,
      employmentStatus: "Full-time",
      notes: "Looking for a 30-year fixed-rate mortgage",
      disabled: true, // Form and actions disabled for this customer
      assign_to_rm: true,
    },
    {
      id: 2,
      name: "Jane Smith",
      address: "456 Oak Ave, Los Angeles, CA 90001",
      requirement: "Personal Loan",
      amount: "$15,000",
      sourcedBy: "Mike Williams",
      mobileNumber: "+1 (555) 234-5678",
      email: "jane.smith@email.com",
      loanType: "Personal Loan",
      income: "$65,000",
      creditScore: 680,
      employmentStatus: "Full-time",
      notes: "Debt consolidation purpose",
      disabled: false, // Form and actions enabled for this customer
      assign_to_rm: false,
    },
    {
      id: 3,
      name: "Robert Johnson",
      address: "789 Pine Rd, Chicago, IL 60601",
      requirement: "Business Loan",
      amount: "$500,000",
      sourcedBy: "Emily Davis",
      mobileNumber: "+1 (555) 345-6789",
      email: "robert.johnson@email.com",
      loanType: "Business Loan",
      income: "$150,000",
      creditScore: 750,
      employmentStatus: "Self-employed",
      notes: "Expanding restaurant business",
      disabled: false, // Form and actions enabled for this customer
      assign_to_rm: false,
    },
    {
      id: 4,
      name: "Maria Garcia",
      address: "321 Elm St, Houston, TX 77001",
      requirement: "Auto Loan",
      amount: "$35,000",
      sourcedBy: "David Brown",
      mobileNumber: "+1 (555) 456-7890",
      email: "maria.garcia@email.com",
      loanType: "Auto Loan",
      income: "$72,000",
      creditScore: 695,
      employmentStatus: "Full-time",
      notes: "New SUV purchase",
      disabled: true, // Form and actions disabled for this customer
      assign_to_rm: false,
    },
    {
      id: 5,
      name: "Michael Chen",
      address: "654 Maple Dr, Phoenix, AZ 85001",
      requirement: "Home Loan",
      amount: "$400,000",
      sourcedBy: "Sarah Johnson",
      mobileNumber: "+1 (555) 567-8901",
      email: "michael.chen@email.com",
      loanType: "Home Loan",
      income: "$125,000",
      creditScore: 780,
      employmentStatus: "Full-time",
      notes: "First-time home buyer",
      disabled: false, // Form and actions enabled for this customer
      assign_to_rm: false,
    },
    {
      id: 6,
      name: "Lisa Anderson",
      address: "987 Cedar Ln, Philadelphia, PA 19101",
      requirement: "Personal Loan",
      amount: "$25,000",
      sourcedBy: "Mike Williams",
      mobileNumber: "+1 (555) 678-9012",
      email: "lisa.anderson@email.com",
      loanType: "Personal Loan",
      income: "$58,000",
      creditScore: 670,
      employmentStatus: "Part-time",
      notes: "Medical expenses",
      disabled: true, // Form and actions disabled for this customer
      assign_to_rm: true,
    },
    {
      id: 7,
      name: "Lisa Anderson",
      address: "987 Cedar Ln, Philadelphia, PA 19101",
      requirement: "Personal Loan",
      amount: "$25,000",
      sourcedBy: "Mike Williams",
      mobileNumber: "+1 (555) 678-9012",
      email: "lisa.anderson@email.com",
      loanType: "Personal Loan",
      income: "$58,000",
      creditScore: 670,
      employmentStatus: "Part-time",
      notes: "Medical expenses",
      disabled: false, // Form and actions enabled for this customer
      assign_to_rm: false,
    },
    {
      id: 8,
      name: "Lisa Anderson",
      address: "987 Cedar Ln, Philadelphia, PA 19101",
      requirement: "Personal Loan",
      amount: "$25,000",
      sourcedBy: "Mike Williams",
      mobileNumber: "+1 (555) 678-9012",
      email: "lisa.anderson@email.com",
      loanType: "Personal Loan",
      income: "$58,000",
      creditScore: 670,
      employmentStatus: "Part-time",
      notes: "Medical expenses",
      disabled: true, // Form and actions disabled for this customer
      assign_to_rm: false,
    },
    {
      id: 9,
      name: "Lisa Anderson",
      address: "987 Cedar Ln, Philadelphia, PA 19101",
      requirement: "Personal Loan",
      amount: "$25,000",
      sourcedBy: "Mike Williams",
      mobileNumber: "+1 (555) 678-9012",
      email: "lisa.anderson@email.com",
      loanType: "Personal Loan",
      income: "$58,000",
      creditScore: 670,
      employmentStatus: "Part-time",
      notes: "Medical expenses",
      disabled: false, // Form and actions enabled for this customer
      assign_to_rm: true,
    },
    {
      id: 10,
      name: "Lisa Anderson",
      address: "987 Cedar Ln, Philadelphia, PA 19101",
      requirement: "Personal Loan",
      amount: "$25,000",
      sourcedBy: "Mike Williams",
      mobileNumber: "+1 (555) 678-9012",
      email: "lisa.anderson@email.com",
      loanType: "Personal Loan",
      income: "$58,000",
      creditScore: 670,
      employmentStatus: "Part-time",
      notes: "Medical expenses",
      disabled: true, // Form and actions disabled for this customer
      assign_to_rm: false,
    },
    {
      id: 11,
      name: "Lisa Anderson",
      address: "987 Cedar Ln, Philadelphia, PA 19101",
      requirement: "Personal Loan",
      amount: "$25,000",
      sourcedBy: "Mike Williams",
      mobileNumber: "+1 (555) 678-9012",
      email: "lisa.anderson@email.com",
      loanType: "Personal Loan",
      income: "$58,000",
      creditScore: 670,
      employmentStatus: "Part-time",
      notes: "Medical expenses",
      disabled: false, // Form and actions enabled for this customer
      assign_to_rm: true,
    },
  ],
};

// Example: Pure Form Schema (like HDFC)
export const HDFCCustomerOnboardingSchema = {
  title: "HDFC Agriculture Instant KCC",
  description: "Please fill in your details to complete the onboarding process",

  sections: [
    {
      id: "aadhaar_section",
      type: "form", // Form-based section
      title: "Aadhaar Verification",
      subtitle: "Verify your identity",
      icon: "fingerprint",
      fields: [
        {
          id: "aadhaar_number",
          type: "text",
          label: "Aadhaar Number",
          placeholder: "Enter your 12 digit Aadhaar number",
          required: true,
          icon: "fingerprint",
          validation: {
            pattern: "^\\d{12}$",
            message: "Aadhaar number must be exactly 12 digits",
          },
        },
        {
          id: "biometric_scan",
          type: "biometric",
          label: "Tap to scan",
          required: false,
        },
        {
          id: "kyc_consent",
          type: "checkbox",
          label:
            "I hereby state that I have no objection for HDFC Bank validating and fetching my e-KYC details from UIDAI through the HDFC Bank e-KYC system and consent to provide my Aadhar number, biometric for Aadhar based KYC. Also I give consent to store my eKYC details for the purpose of KYC verification process with HDFC Bank.",
          required: true,
          validation: {
            message: "You must accept the terms to continue",
          },
        },
      ],
    },

    {
      id: "applicant_details",
      type: "form",
      title: "Applicant Details",
      subtitle: "Personal information",
      icon: "person",
      fields: [
        {
          id: "full_name",
          type: "text",
          label: "Full Name",
          placeholder: "Enter your full name",
          required: true,
          icon: "person",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            minLength: 3,
            message: "Full name must be at least 3 characters",
          },
        },
        {
          id: "date_of_birth",
          type: "date",
          label: "Date Of Birth",
          required: true,
          icon: "calendar",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            maxDate: "2006-01-01",
            message: "Date of birth must be before 2006",
          },
        },
        {
          id: "gender",
          type: "radio",
          label: "Gender",
          required: true,
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            message: "Please select a gender",
          },
          options: [
            { value: "male", label: "Male", icon: "male" },
            { value: "female", label: "Female", icon: "female" },
            { value: "transgender", label: "Transgender", icon: "transgender" },
          ],
        },
        {
          id: "care_of",
          type: "text",
          label: "C/O",
          placeholder: "Care of",
          required: false,
          icon: "home",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
        },
        {
          id: "father_name",
          type: "text",
          label: "Father Name",
          placeholder: "Enter father's name",
          required: true,
          icon: "person",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
        },
        {
          id: "mother_name",
          type: "text",
          label: "Mother Name",
          placeholder: "Enter mother's name",
          required: true,
          icon: "person",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
        },
        {
          id: "pan_card_image",
          type: "image_capture",
          label: "PAN Card",
          placeholder: "Capture or upload your PAN card",
          required: true,
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            message: "PAN card image is required",
          },
        },
        {
          id: "customer_photo",
          type: "image_capture",
          label: "Customer Photo",
          placeholder: "Capture or upload your photo",
          required: true,
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            message: "Customer photo is required",
          },
        },
      ],
    },

    {
      id: "contact_details",
      type: "form",
      title: "Contact Information",
      subtitle: "How can we reach you",
      icon: "phone",
      fields: [
        {
          id: "mobile_number",
          type: "tel",
          label: "Mobile Number",
          placeholder: "Enter 10 digit mobile number",
          required: true,
          icon: "phone",
          validation: {
            pattern: "^\\d{10}$",
            message: "Mobile number must be exactly 10 digits",
          },
        },
        {
          id: "email",
          type: "email",
          label: "Email Address",
          placeholder: "Enter your email",
          required: true,
          icon: "email",
          validation: {
            pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
            message: "Please enter a valid email address",
          },
        },
        {
          id: "address",
          type: "text",
          label: "Address",
          placeholder: "Enter your complete address",
          required: true,
          multiline: true,
          rows: 3,
        },
      ],
    },
  ],

  submitButton: {
    label: "Submit Application",
    action: "submit",
  },
};
