// Unified Generic Schema Format
// Supports both form-based and component-based sections

export const HDFCLeadManagementConfig = {
  title: "HDFC Agri Funds",
  description: "Manage leads and track customer onboarding progress",

  // Layout & Responsive Configuration
  layout: {
    // Main container alignment
    containerAlignment: "flex-start", // flex-start, center, flex-end, space-between
    containerPadding: { xs: 1, sm: 2, md: 3, lg: 4 }, // Responsive padding
    gap: { xs: 1, sm: 2, md: 3 }, // Gap between main content and sidebar

    // Card grid configuration
    cardGrid: {
      columns: { xs: 1, sm: 1, md: 2, lg: 2, xl: 3 }, // Responsive columns (optimized for laptop)
      gap: 2, // Gap between cards
      autoRows: "1fr", // Equal height rows
    },

    // Breakpoints (Material-UI standard)
    breakpoints: {
      xs: 0, // Mobile
      sm: 600, // Tablet
      md: 960, // Small laptop
      lg: 1280, // Desktop
      xl: 1920, // Large desktop
    },
  },

  // Right Sidebar Configuration
  sidebar: {
    // Responsive widths (increased by ~15%)
    width: {
      xs: "100%", // Full width on mobile
      sm: 440, // Compact on tablet (380 + 15% ≈ 440)
      md: 485, // Medium on small laptop (420 + 15% ≈ 485)
      lg: 550, // Comfortable on desktop (480 + 15% ≈ 550)
      xl: 645, // Spacious on large screens (560 + 15% ≈ 645)
    },
    alwaysOpen: true, // Always visible as sidebar
    position: "fixed", // Fixed position for true sidebar
    top: 64, // Start below navbar (64px AppBar height)
    right: 0, // Flush with right
    maxHeight: "calc(100vh - 64px)", // Full viewport height minus navbar

    // Control Panel Layout
    controlPanel: {
      padding: 2,
      filterLayout: "grid", // grid (side-by-side) or stack (vertical)
      filterColumns: { xs: 1, sm: 2, md: 2 }, // Responsive filter columns
      filterGap: 2,
      compactMode: { xs: true, sm: true, md: false }, // Compact on smaller screens
    },

    customerView: {
      enabled: true,
      title: "Customer Details",
      showFormSchema: true,
      readOnlyByDefault: true,
      actions: [
        {
          id: "reject",
          label: "Reject",
          variant: "outlined",
          color: "error",
          action: "reject",
          fullWidth: true,
        },
        {
          id: "approve",
          label: "Approve",
          variant: "contained",
          color: "success",
          action: "approve",
          fullWidth: true,
        },
      ],
    },
    tabs: [
      {
        id: "control_panel",
        type: "control_panel",
        label: "Control",
        icon: "Dashboard",
        badge: null,
        items: [
          {
            icon: "Dashboard",
            label: "Dashboard Overview",
            description: "View analytics and reports",
            badge: null,
          },
          {
            icon: "FilterList",
            label: "Advanced Filters",
            description: "Customize your view",
            badge: "8",
          },
          {
            icon: "Notifications",
            label: "Notifications",
            description: "Manage alerts",
            badge: "12",
          },
        ],
      },
      {
        id: "messages",
        type: "messages",
        label: "Messages",
        icon: "Message",
        badge: 3,
        messages: [
          {
            sender: "Priya Nair",
            time: "2m ago",
            message:
              "Can you review Nikhil's application? It's been pending for 2 days.",
            read: false,
          },
          {
            sender: "Rahul Verma",
            time: "1h ago",
            message:
              "The documents for Ananya Gupta have been uploaded successfully.",
            read: false,
          },
          {
            sender: "Suresh Kumar",
            time: "3h ago",
            message:
              "Meeting scheduled for tomorrow at 10 AM to discuss Q4 targets.",
            read: true,
          },
          {
            sender: "Meera Rathore",
            time: "5h ago",
            message:
              "Client called regarding loan approval timeline. Please follow up.",
            read: false,
          },
        ],
      },
      {
        id: "chat",
        type: "chat",
        label: "Chat",
        icon: "Chat",
        badge: 5,
        chats: [
          {
            name: "Team Support",
            lastMessage: "Sure, I'll look into it right away!",
            unread: 2,
          },
          {
            name: "Priya Nair",
            lastMessage: "Thanks for the update 👍",
            unread: 0,
          },
          {
            name: "Credit Review Team",
            lastMessage: "Application #AG_HD_DA_6969 approved",
            unread: 3,
          },
          {
            name: "Rahul Verma",
            lastMessage: "Can we schedule a call?",
            unread: 0,
          },
        ],
      },
      {
        id: "alerts",
        type: "alerts",
        label: "Alerts",
        icon: "Notifications",
        badge: 4,
        alerts: [
          {
            icon: "Warning",
            severity: "error",
            title: "Urgent Review Required",
            message: "3 applications pending for more than 48 hours",
          },
          {
            icon: "Error",
            severity: "error",
            title: "Document Expired",
            message: "KYC documents for 2 customers need renewal",
          },
          {
            icon: "Warning",
            severity: "warning",
            title: "Credit Score Alert",
            message: "1 applicant below minimum threshold (650)",
          },
          {
            icon: "CheckCircle",
            severity: "success",
            title: "Target Achieved",
            message: "Monthly disbursement target of ₹2Cr reached!",
          },
        ],
      },
      {
        id: "filters",
        type: "filters",
        label: "Filters",
        icon: "FilterList",
        badge: null,
        filterGroups: [
          {
            label: "Approval Status",
            filters: [
              { label: "Pending", count: 7, active: false },
              { label: "Approved", count: 4, active: false },
              { label: "Rejected", count: 5, active: false },
            ],
          },
          {
            label: "Loan Type",
            filters: [
              { label: "Agri Loan", count: 5, active: false },
              { label: "Individual", count: 6, active: false },
              { label: "Car Loan", count: 2, active: false },
              { label: "Joint Liability", count: 3, active: false },
            ],
          },
          {
            label: "Stage",
            filters: [
              { label: "Leads Only", count: 2, active: false },
              { label: "L1 Submitted", count: 3, active: false },
              { label: "L2 Submitted", count: 4, active: false },
              { label: "Bank Details", count: 2, active: false },
              { label: "eSign Pending", count: 5, active: false },
            ],
          },
        ],
      },
    ],
  },

  sections: [
    {
      id: "header_section",
      type: "component",
      componentType: "header",
      title: "HDFC Agri Funds",
      // subtitle: "Anchor Corporate Portal",
      icon: "list",
      config: {},
    },
    {
      id: "filter_section",
      type: "component",
      componentType: "filter",
      title: "Filter by Stage",
      subtitle: "Filter leads by their current stage",
      icon: "filter",
      config: {
        layout: "three-column", // Three-column layout with dividers
        showDividers: true, // Show vertical dividers between sections
        sections: [
          {
            id: "search_section",
            type: "search",
            label: "Search",
            flex: 1,
            minWidth: 250,
            placeholder: "Search by name, address, requirement, or phone...",
            searchableFields: [
              "name",
              "address",
              "requirement",
              "sourcedBy",
              "mobileNumber",
            ],
          },
          {
            id: "stage_filters",
            type: "stage",
            label: "Stage",
            flex: 1.5,
            minWidth: 300,
            filters: [
              {
                id: "all",
                label: "All",
                value: "all",
                filterKey: null,
              },
              {
                id: "leads_only",
                label: "Leads Only",
                value: "leads_only",
                filterKey: "formSchemaId",
                filterValue: null,
              },
              {
                id: "l1_submitted",
                label: "L1 Submitted",
                value: "l1_submitted",
                filterKey: "formSchemaId",
                filterValue: "l1_customer_info",
              },
              {
                id: "l2_submitted",
                label: "L2 Submitted (KCC)",
                value: "l2_submitted",
                filterKey: "formSchemaId",
                filterValue: "instant_kcc",
              },
              {
                id: "bank_details",
                label: "Bank Account Details",
                value: "bank_details",
                filterKey: "formSchemaId",
                filterValue: "bank_account_details",
              },
              {
                id: "esign_pending",
                label: "eSign Pending",
                value: "esign_pending",
                filterKey: "formSchemaId",
                filterValue: "esign_documents",
              },
            ],
          },
          {
            id: "approval_filters",
            type: "approval",
            label: "Approval Status",
            flex: 1,
            minWidth: 300,
            filters: [
              {
                id: "all",
                label: "All",
                value: "all",
                color: "primary.main",
              },
              {
                id: "pending",
                label: "Pending",
                value: "pending",
                color: "#ed6c02",
              },
              {
                id: "approved",
                label: "Approved",
                value: "approved",
                color: "#2e7d32",
              },
              {
                id: "rejected",
                label: "Rejected",
                value: "rejected",
                color: "#d32f2f",
              },
            ],
          },
        ],
        // Legacy filters array for backward compatibility
        filters: [
          {
            id: "all",
            label: "All",
            value: "all",
            filterKey: null,
          },
          {
            id: "leads_only",
            label: "Leads Only",
            value: "leads_only",
            filterKey: "formSchemaId",
            filterValue: null,
          },
          {
            id: "l1_submitted",
            label: "L1 Submitted",
            value: "l1_submitted",
            filterKey: "formSchemaId",
            filterValue: "l1_customer_info",
          },
          {
            id: "l2_submitted",
            label: "L2 Submitted (KCC)",
            value: "l2_submitted",
            filterKey: "formSchemaId",
            filterValue: "instant_kcc",
          },
          {
            id: "bank_details",
            label: "Bank Account Details",
            value: "bank_details",
            filterKey: "formSchemaId",
            filterValue: "bank_account_details",
          },
          {
            id: "esign_pending",
            label: "eSign Pending",
            value: "esign_pending",
            filterKey: "formSchemaId",
            filterValue: "esign_documents",
          },
        ],
      },
    },
    {
      id: "search_section",
      type: "component",
      componentType: "search",
      title: "Search Leads",
      subtitle: "Find prospects quickly",
      icon: "search",
      config: {
        placeholder: "Search by name, address, requirement, or phone...",
        maxWidth: 600,
        startIcon: "Search",
        searchableFields: [
          "name",
          "address",
          "requirement",
          "sourcedBy",
          "mobileNumber",
        ],
        showCount: true,
        countLabel: "prospect",
        emptyMessage: "No prospects found",
        emptyHint: "Try adjusting your search criteria",
      },
    },
    {
      id: "leads_list_section",
      type: "component",
      componentType: "cardList",
      title: "Leads List",
      subtitle: "View all prospects",
      icon: "list",
      config: {
        idKey: "id",
        cardStyle: "modern", // New modern card style
        header: {
          showAvatar: true,
          avatarKey: "avatarUrl", // Use avatarUrl instead of name
          avatarSize: 56,
          titleKey: "name",
          minHeight: "80px",
          avatarFallbackKey: "name", // Fallback to name if no avatarUrl
        },
        // Left side info fields
        fields: [
          {
            id: "product",
            dataKey: "loanType",
            icon: "AccountBalance",
            iconSize: 18,
            fontSize: "0.875rem",
            minHeight: "24px",
            label: "Product",
            fontWeight: 500,
          },
          {
            id: "location",
            dataKey: "address",
            icon: "LocationOn",
            iconSize: 18,
            fontSize: "0.85rem",
            alignItems: "flex-start",
            minHeight: "24px",
            clamp: 1,
            label: "Location",
          },
        ],
        // Right side metrics/data points (4-5 dynamic metrics per lead)
        metrics: [
          {
            id: "creditScore",
            dataKey: "creditScore",
            label: "Credit Score",
            icon: "CheckCircle",
            iconSize: 18,
            fontSize: "1rem",
            fontWeight: 700,
            color: "#2e7d32",
            bgColor: "#2e7d32",
            showLabel: true,
          },
          {
            id: "region",
            dataKey: "region",
            label: "Region",
            icon: "LocationOn",
            iconSize: 18,
            fontSize: "0.85rem",
            fontWeight: 600,
            color: "#1976d2",
            bgColor: "#1976d2",
            showLabel: true,
          },
          {
            id: "productType",
            dataKey: "productType",
            label: "Product",
            icon: "AccountBalance",
            iconSize: 18,
            fontSize: "0.8rem",
            fontWeight: 600,
            color: "#9c27b0",
            bgColor: "#9c27b0",
            showLabel: true,
          },
          {
            id: "amount",
            dataKey: "amount",
            label: "Amount",
            icon: "CurrencyRupee",
            iconSize: 18,
            fontSize: "0.85rem",
            fontWeight: 700,
            color: "#ed6c02",
            bgColor: "#ed6c02",
            showLabel: true,
          },
        ],
        // Review button configuration
        actions: {
          showButton: true,
          buttonLabel: "Review",
          buttonVariant: "contained",
          buttonSize: "small",
          buttonIcon: "ArrowForward",
          buttonFullWidth: true,
        },
      },
    },

    {
      id: "lead_details_dialog",
      type: "dialog",
      title: "Lead Details",
      maxWidth: "md",
      fullWidth: true,

      // Dialog can have form sections inside
      sections: [
        {
          id: "lead_info_form",
          type: "form", // Form-based section inside dialog
          title: "Lead Information",
          subtitle: "Complete lead details",
          icon: "person",
          fields: [
            {
              id: "name",
              type: "text",
              label: "Full Name",
              dataKey: "name",
              placeholder: "Enter full name",
              required: true,
              icon: "person",
              xs: 12,
              md: 6,
            },
            {
              id: "mobileNumber",
              type: "text",
              label: "Mobile Number",
              dataKey: "mobileNumber",
              placeholder: "Enter mobile number",
              required: true,
              icon: "phone",
              xs: 12,
              md: 6,
              validation: {
                pattern: "^\\d{10}$",
                message: "Mobile number must be exactly 10 digits",
              },
            },
            {
              id: "email",
              type: "email",
              label: "Email",
              dataKey: "email",
              placeholder: "Enter email address",
              required: true,
              icon: "email",
              xs: 12,
              md: 6,
              validation: {
                pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
                message: "Please enter a valid email address",
              },
            },
            {
              id: "address",
              type: "text",
              label: "Address",
              dataKey: "address",
              placeholder: "Enter address",
              icon: "home",
              xs: 12,
              md: 6,
            },
            {
              id: "requirement",
              type: "select",
              label: "Requirement",
              dataKey: "requirement",
              placeholder: "Select requirement",
              xs: 12,
              md: 6,
              options: [
                { value: "Home Loan", label: "Home Loan" },
                { value: "Personal Loan", label: "Personal Loan" },
                { value: "Business Loan", label: "Business Loan" },
                { value: "Auto Loan", label: "Auto Loan" },
              ],
            },
            {
              id: "amount",
              type: "text",
              label: "Amount",
              dataKey: "amount",
              placeholder: "Enter amount",
              xs: 12,
              md: 6,
            },
            {
              id: "loanType",
              type: "select",
              label: "Loan Type",
              dataKey: "loanType",
              placeholder: "Select loan type",
              xs: 12,
              md: 6,
              options: [
                { value: "Home Loan", label: "Home Loan" },
                { value: "Personal Loan", label: "Personal Loan" },
                { value: "Business Loan", label: "Business Loan" },
                { value: "Auto Loan", label: "Auto Loan" },
              ],
            },
            {
              id: "sourcedBy",
              type: "text",
              label: "Sourced By",
              dataKey: "sourcedBy",
              placeholder: "Enter source name",
              icon: "person",
              xs: 12,
              md: 6,
            },
            {
              id: "income",
              type: "text",
              label: "Annual Income",
              dataKey: "income",
              placeholder: "Enter annual income",
              xs: 12,
              md: 4,
            },
            {
              id: "creditScore",
              type: "number",
              label: "Credit Score",
              dataKey: "creditScore",
              placeholder: "Enter credit score",
              xs: 12,
              md: 4,
            },
            {
              id: "employmentStatus",
              type: "select",
              label: "Employment Status",
              dataKey: "employmentStatus",
              placeholder: "Select employment status",
              xs: 12,
              md: 4,
              options: [
                { value: "Full-time", label: "Full-time" },
                { value: "Part-time", label: "Part-time" },
                { value: "Self-employed", label: "Self-employed" },
                { value: "Unemployed", label: "Unemployed" },
              ],
            },
            {
              id: "notes",
              type: "text",
              label: "Notes",
              dataKey: "notes",
              placeholder: "Enter any additional notes",
              multiline: true,
              rows: 3,
              xs: 12,
            },
          ],
        },
      ],

      // Dialog actions
      actions: [
        {
          id: "accept",
          label: "Accept",
          action: "accept",
          variant: "contained",
          color: "success",
          showIf: "viewing",
        },
        {
          id: "reject",
          label: "Reject",
          action: "reject",
          variant: "contained",
          color: "error",
          showIf: "viewing",
        },
        {
          id: "assign_to_rm",
          label: "Assign to RM",
          action: "assign_to_rm",
          variant: "contained",
          color: "warning",
          showIf: "viewing",
        },
      ],
    },
  ],

  // Data source
  data: [
    {
      id: 1,
      name: "Nikhil Kamath",
      avatarUrl: "https://i.pravatar.cc/150?img=12",
      address: "Mumbai",
      region: "West",
      productType: "KCC",
      amount: "₹18L",
      requirement: "Agri Loan",
      desiredProduct: "Kisan Credit Card",
      status: "Lead Generated",
      sourcedBy: "Priya Nair",
      mobileNumber: "9876543210",
      email: "rohit.sharma@example.in",
      loanType: "Individual Farmer Loan",
      income: "INR 18,00,000",
      creditScore: 785,
      employmentStatus: "Full-time",
      notes: "Upgrading to a larger apartment near Powai Lake",
      disabled: false,
      assign_to_rm: true,
      approvalStatus: "approved",
    },
    {
      id: 2,
      name: "Ananya Gupta",
      avatarUrl: "https://i.pravatar.cc/150?img=47",
      address: "Indiranagar,",
      region: "South",
      productType: "Term",
      amount: "₹9.2L",
      requirement: "Agri Loan",
      mifixId: "AG_HD_DA_6969",
      desiredProduct: "Agri Term Loan",
      status: "L1 Info Pending",
      sourcedBy: "Rahul Verma",
      mobileNumber: "9988776655",
      email: "ananya.gupta@example.in",
      loanType: "Agri Loan",
      income: "INR 9,20,000",
      creditScore: 732,
      employmentStatus: "Full-time",
      notes: "Funding higher studies for younger brother",
      disabled: false,
      assign_to_rm: false,
      formSchemaId: "l1_customer_info",
      formSchemas: ["l1_customer_info"],
      approvalStatus: "pending",
    },
    {
      id: 3,
      name: "Nithin Kamath",
      avatarUrl: "https://i.pravatar.cc/150?img=33",
      address: "Chennai",
      region: "South",
      productType: "KCC",
      amount: "₹1.85Cr",
      requirement: "Agri Loan",
      mifixId: "AG_HD_CH_103",
      desiredProduct: "Kisan Credit Card",
      status: "KCC Details Pending",
      sourcedBy: "Neha Kulkarni",
      mobileNumber: "9123456780",
      email: "suresh.iyer@example.in",
      loanType: "Agri Loan",
      income: "INR 45,00,000",
      creditScore: 768,
      employmentStatus: "Self-employed",
      notes: "Expanding textile manufacturing unit in Ambattur",
      disabled: false,
      assign_to_rm: true,
      formSchemaId: "instant_kcc",
      formSchemas: ["l1_customer_info", "instant_kcc"],
      approvalStatus: "approved",
    },
    {
      id: 4,
      name: "Meera Reddy",
      avatarUrl: "https://i.pravatar.cc/150?img=49",
      address: "Villa 14, Road 92, Jubilee Hills, Hyderabad - 500033",
      region: "South",
      productType: "Vehicle",
      amount: "₹28L",
      requirement: "Car Loan",
      mifixId: "CL_HD_HY_204",
      desiredProduct: "Vehicle Loan",
      status: "Bank Details Required",
      sourcedBy: "Aditya Rao",
      mobileNumber: "9012345678",
      email: "meera.reddy@example.in",
      loanType: "Car Loan",
      income: "INR 16,50,000",
      creditScore: 710,
      employmentStatus: "Full-time",
      notes: "Leasing an electric SUV for corporate commute",
      disabled: true,
      assign_to_rm: false,
      formSchemaId: "bank_account_details",
      formSchemas: ["l1_customer_info", "instant_kcc", "bank_account_details"],
      approvalStatus: "rejected",
    },
    {
      id: 5,
      name: "Arjun Patel",
      avatarUrl: "https://i.pravatar.cc/150?img=60",
      address: "Ahmedabad ",
      region: "West",
      productType: "Home",
      amount: "₹55L",
      requirement: "Individual Loan",
      mifixId: "IL_HD_AH_305",
      desiredProduct: "Home Loan",
      status: "eSign Pending",
      sourcedBy: "Sonal Shah",
      mobileNumber: "9825076543",
      email: "arjun.patel@example.in",
      loanType: "Individual Loan",
      income: "INR 22,50,000",
      creditScore: 805,
      employmentStatus: "Full-time",
      notes: "First-time buyer eligible for PMAY subsidy",
      disabled: false,
      assign_to_rm: false,
      formSchemaId: "esign_documents",
      formSchemas: [
        "l1_customer_info",
        "instant_kcc",
        "bank_account_details",
        "esign_documents",
      ],
      approvalStatus: "pending",
    },
    {
      id: 6,
      name: "Lata Menon",
      avatarUrl: "https://i.pravatar.cc/150?img=44",
      address: "16 Residency Road, Panampilly Nagar, Kochi - 682011",
      region: "South",
      productType: "Medical",
      amount: "₹4.25L",
      requirement: "Individual Loan",
      mifixId: "IL_HD_KO_406",
      desiredProduct: "Medical Loan",
      status: "L1 Info Pending",
      sourcedBy: "Vishal Pillai",
      mobileNumber: "9847001122",
      email: "lata.menon@example.in",
      loanType: "Individual Loan",
      income: "INR 7,40,000",
      creditScore: 705,
      employmentStatus: "Part-time",
      notes: "Planned cardiac procedure at Aster Medcity",
      disabled: true,
      assign_to_rm: true,
      formSchemaId: "l1_customer_info",
      formSchemas: ["l1_customer_info"],
      approvalStatus: "rejected",
    },
    {
      id: 7,
      name: "Devanshi Mehta",
      avatarUrl: "https://i.pravatar.cc/150?img=45",
      address: "Jaipur",
      region: "North",
      productType: "Business",
      amount: "₹32L",
      requirement: "Joint Liability Loan",
      mifixId: "JL_HD_JP_507",
      desiredProduct: "Business Loan",
      status: "KCC Details Pending",
      sourcedBy: "Karan Batra",
      mobileNumber: "9799887766",
      email: "devanshi.mehta@example.in",
      loanType: "Joint Liability Loan",
      income: "INR 21,00,000",
      creditScore: 742,
      employmentStatus: "Self-employed",
      notes: "Setting up a boutique handicraft studio for exports",
      disabled: false,
      assign_to_rm: false,
      formSchemaId: "instant_kcc",
      formSchemas: ["l1_customer_info", "instant_kcc"],
      approvalStatus: "pending",
    },
    {
      id: 8,
      name: "Farhan Bin Khan",
      avatarUrl: "https://i.pravatar.cc/150?img=51",
      address: "Flat 8C, Park Circus, Kolkata - 700017",
      region: "East",
      productType: "Personal",
      amount: "₹8.2L",
      requirement: "Car Loan",
      mifixId: "CL_HD_KL_608",
      desiredProduct: "Personal Loan",
      status: "Bank Details Required",
      sourcedBy: "Sangeeta Bose",
      mobileNumber: "9830012345",
      email: "farhan.khan@example.in",
      loanType: "Car Loan",
      income: "INR 10,50,000",
      creditScore: 688,
      employmentStatus: "Full-time",
      notes: "Home renovation and modular kitchen upgrade",
      disabled: true,
      assign_to_rm: false,
      formSchemaId: "bank_account_details",
      formSchemas: ["l1_customer_info", "instant_kcc", "bank_account_details"],
      approvalStatus: "rejected",
    },
    {
      id: 9,
      name: "Neha Deshpande",
      address: "3F, Baner Pashan Link Road, Pune - 411021",
      requirement: "Agri Loan",
      amount: "INR 48,00,000",
      mifixId: "AG_HD_PN_709",
      desiredProduct: "Agri Term Loan",
      status: "eSign Pending",
      sourcedBy: "Mahesh Patil",
      mobileNumber: "9090909090",
      email: "neha.deshpande@example.in",
      loanType: "Agri Loan",
      income: "INR 13,20,000",
      creditScore: 752,
      employmentStatus: "Full-time",
      notes: "Purchasing 2 BHK close to Hinjewadi IT park",
      disabled: false,
      assign_to_rm: true,
      formSchemaId: "esign_documents",
      formSchemas: [
        "l1_customer_info",
        "instant_kcc",
        "bank_account_details",
        "esign_documents",
      ],
      approvalStatus: "approved",
    },
    {
      id: 10,
      name: "Gaganpreet Singh",
      address: "Chandigarh",
      requirement: "Joint Liability Loan",
      amount: "INR 65,00,000",
      mifixId: "JL_HD_CH_810",
      desiredProduct: "Commercial Vehicle Loan",
      status: "L1 Info Pending",
      sourcedBy: "Harleen Kaur",
      mobileNumber: "9878001234",
      email: "gaganpreet.singh@example.in",
      loanType: "Joint Liability Loan",
      income: "INR 27,50,000",
      creditScore: 739,
      employmentStatus: "Self-employed",
      notes: "Expanding refrigerated transport fleet for pharma",
      disabled: false,
      assign_to_rm: false,
      formSchemaId: "l1_customer_info",
      formSchemas: ["l1_customer_info"],
      approvalStatus: "pending",
    },
    {
      id: 11,
      name: "Aahana Mukherjee",
      address: "Block D, 18/2 Salt Lake, Kolkata - 700091",
      requirement: "Individual Loan",
      amount: "INR 3,80,000",
      mifixId: "IL_HD_KL_911",
      desiredProduct: "Wedding Loan",
      status: "KCC Details Pending",
      sourcedBy: "Debashish Sen",
      mobileNumber: "9903123456",
      email: "aahana.mukherjee@example.in",
      loanType: "Individual Loan",
      income: "INR 6,80,000",
      creditScore: 702,
      employmentStatus: "Full-time",
      notes: "Destination wedding planning expenses in Goa",
      disabled: true,
      assign_to_rm: true,
      formSchemaId: "instant_kcc",
      formSchemas: ["l1_customer_info", "instant_kcc"],
      approvalStatus: "rejected",
    },
    {
      id: 12,
      name: "Rajesh Kumar",
      address: "Chandigarh",
      requirement: "Joint Liability Loan",
      amount: "INR 92,00,000",
      mifixId: "JL_HD_CH_912",
      desiredProduct: "Warehouse Loan",
      status: "L1 Info Pending",
      sourcedBy: "Simran Kaur",
      mobileNumber: "9878123456",
      email: "rajesh.kumar@example.in",
      loanType: "Joint Liability Loan",
      income: "INR 38,00,000",
      creditScore: 772,
      employmentStatus: "Self-employed",
      notes: "Expanding cold storage facility for agricultural products",
      disabled: false,
      assign_to_rm: false,
      formSchemaId: "l1_customer_info",
      formSchemas: ["l1_customer_info"],
      approvalStatus: "pending",
    },
    {
      id: 13,
      name: "Priya Deshmukh",
      address: "Nagpur",
      requirement: "Individual Loan",
      amount: "INR 15,00,000",
      mifixId: "IL_HD_NG_1013",
      desiredProduct: "Education Loan",
      status: "Bank Details Required",
      sourcedBy: "Anand Pathak",
      mobileNumber: "9823456789",
      email: "priya.deshmukh@example.in",
      loanType: "Individual Loan",
      income: "INR 8,50,000",
      creditScore: 745,
      employmentStatus: "Full-time",
      notes: "MBA program at IIM Bangalore",
      disabled: false,
      assign_to_rm: false,
      formSchemaId: "bank_account_details",
      formSchemas: ["l1_customer_info", "instant_kcc", "bank_account_details"],
      approvalStatus: "pending",
    },
    {
      id: 14,
      name: "Vikram Singh Rathore",
      address: "Palace Road Extension, Udaipur - 313001",
      requirement: "Car Loan",
      amount: "INR 45,00,000",
      mifixId: "CL_HD_UD_1114",
      desiredProduct: "Luxury Car Loan",
      status: "eSign Pending",
      sourcedBy: "Meera Rathore",
      mobileNumber: "9414567890",
      email: "vikram.rathore@example.in",
      loanType: "Car Loan",
      income: "INR 25,00,000",
      creditScore: 788,
      employmentStatus: "Self-employed",
      notes: "Heritage hotel owner purchasing Tesla Model 3",
      disabled: false,
      assign_to_rm: true,
      formSchemaId: "esign_documents",
      formSchemas: [
        "l1_customer_info",
        "instant_kcc",
        "bank_account_details",
        "esign_documents",
      ],
      approvalStatus: "approved",
    },
    {
      id: 15,
      name: "Anjali Menon",
      address: "Thiruvananthapuram",
      requirement: "Agri Loan",
      amount: "INR 22,00,000",
      mifixId: "AG_HD_TV_1215",
      desiredProduct: "Fishery Loan",
      status: "L2 Info Pending",
      sourcedBy: "Suresh Pillai",
      mobileNumber: "9447123456",
      email: "anjali.menon@example.in",
      loanType: "Agri Loan",
      income: "INR 12,00,000",
      creditScore: 758,
      employmentStatus: "Self-employed",
      notes: "Expanding prawn farming business",
      disabled: false,
      assign_to_rm: false,
      formSchemaId: "instant_kcc",
      formSchemas: ["l1_customer_info", "instant_kcc"],
      approvalStatus: "pending",
    },
    {
      id: 16,
      name: "Mohit Sharma",
      address: "Sector 15, Faridabad - 121007",
      requirement: "Individual Loan",
      amount: "INR 8,50,000",
      mifixId: "IL_HD_FD_1316",
      desiredProduct: "Medical Loan",
      status: "KCC Details Pending",
      sourcedBy: "Rakesh Gupta",
      mobileNumber: "9650123456",
      email: "mohit.sharma@example.in",
      loanType: "Individual Loan",
      income: "INR 5,80,000",
      creditScore: 692,
      employmentStatus: "Full-time",
      notes: "Knee replacement surgery at Fortis Hospital",
      disabled: true,
      assign_to_rm: false,
      formSchemaId: "instant_kcc",
      formSchemas: ["l1_customer_info", "instant_kcc"],
      approvalStatus: "rejected",
    },
  ],
};

// Example: Pure Form Schema (like HDFC)
export const HDFCCustomerOnboardingSchema = {
  title: "HDFC Agriculture Instant KCC",
  description: "Please fill in your details to complete the onboarding process",

  sections: [
    {
      id: "aadhaar_section",
      type: "form", // Form-based section
      title: "Aadhaar Verification",
      subtitle: "Verify your identity",
      icon: "fingerprint",
      fields: [
        {
          id: "aadhaar_number",
          type: "text",
          label: "Aadhaar Number",
          placeholder: "Enter your 12 digit Aadhaar number",
          required: true,
          icon: "fingerprint",
          validation: {
            pattern: "^\\d{12}$",
            message: "Aadhaar number must be exactly 12 digits",
          },
        },
        {
          id: "biometric_scan",
          type: "biometric",
          label: "Tap to scan",
          required: false,
        },
        {
          id: "kyc_consent",
          type: "checkbox",
          label:
            "I hereby state that I have no objection for HDFC Bank validating and fetching my e-KYC details from UIDAI through the HDFC Bank e-KYC system and consent to provide my Aadhar number, biometric for Aadhar based KYC. Also I give consent to store my eKYC details for the purpose of KYC verification process with HDFC Bank.",
          required: true,
          validation: {
            message: "You must accept the terms to continue",
          },
        },
      ],
    },

    {
      id: "applicant_details",
      type: "form",
      title: "Applicant Details",
      subtitle: "Personal information",
      icon: "person",
      fields: [
        {
          id: "full_name",
          type: "text",
          label: "Full Name",
          placeholder: "Enter your full name",
          required: true,
          icon: "person",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            minLength: 3,
            message: "Full name must be at least 3 characters",
          },
        },
        {
          id: "date_of_birth",
          type: "date",
          label: "Date Of Birth",
          required: true,
          icon: "calendar",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            maxDate: "2006-01-01",
            message: "Date of birth must be before 2006",
          },
        },
        {
          id: "gender",
          type: "radio",
          label: "Gender",
          required: true,
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            message: "Please select a gender",
          },
          options: [
            { value: "male", label: "Male", icon: "male" },
            { value: "female", label: "Female", icon: "female" },
            { value: "transgender", label: "Transgender", icon: "transgender" },
          ],
        },
        {
          id: "care_of",
          type: "text",
          label: "C/O",
          placeholder: "Care of",
          required: false,
          icon: "home",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
        },
        {
          id: "father_name",
          type: "text",
          label: "Father Name",
          placeholder: "Enter father's name",
          required: true,
          icon: "person",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
        },
        {
          id: "mother_name",
          type: "text",
          label: "Mother Name",
          placeholder: "Enter mother's name",
          required: true,
          icon: "person",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
        },
        {
          id: "pan_card_image",
          type: "image_capture",
          label: "PAN Card",
          placeholder: "Capture or upload your PAN card",
          required: true,
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            message: "PAN card image is required",
          },
        },
        {
          id: "customer_photo",
          type: "image_capture",
          label: "Customer Photo",
          placeholder: "Capture or upload your photo",
          required: true,
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            message: "Customer photo is required",
          },
        },
      ],
    },

    {
      id: "contact_details",
      type: "form",
      title: "Contact Information",
      subtitle: "How can we reach you",
      icon: "phone",
      fields: [
        {
          id: "mobile_number",
          type: "tel",
          label: "Mobile Number",
          placeholder: "Enter 10 digit mobile number",
          required: true,
          icon: "phone",
          validation: {
            pattern: "^\\d{10}$",
            message: "Mobile number must be exactly 10 digits",
          },
        },
        {
          id: "email",
          type: "email",
          label: "Email Address",
          placeholder: "Enter your email",
          required: true,
          icon: "email",
          validation: {
            pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
            message: "Please enter a valid email address",
          },
        },
        {
          id: "address",
          type: "text",
          label: "Address",
          placeholder: "Enter your complete address",
          required: true,
          multiline: true,
          rows: 3,
        },
      ],
    },
  ],

  submitButton: {
    label: "Submit Application",
    action: "submit",
  },
};
