// Unified Generic Schema Format
// Supports both form-based and component-based sections

export const LeadsManagementSchema = {
  title: "Lead Management",
  description: "Manage and track customer leads",
  sections: [
    {
      id: "header_section",
      type: "component",
      componentType: "header",
      title: "HDFC Agri Funds",
      subtitle: "Anchor Corporate Portal",
      icon: "list",
      config: {},
    },
    {
      id: "search_section",
      type: "component",
      componentType: "search",
      title: "Search Leads",
      subtitle: "Find prospects quickly",
      icon: "search",
      config: {
        placeholder: "Search by name, address, requirement, or phone...",
        maxWidth: 600,
        startIcon: "Search",
        searchableFields: [
          "name",
          "address",
          "requirement",
          "sourcedBy",
          "mobileNumber",
        ],
        showCount: true,
        countLabel: "prospect",
        emptyMessage: "No prospects found",
        emptyHint: "Try adjusting your search criteria",
      },
    },

    {
      id: "leads_list_section",
      type: "component",
      componentType: "cardList",
      title: "Leads List",
      subtitle: "View all prospects",
      icon: "list",
      config: {
        idKey: "id",
        header: {
          showAvatar: true,
          avatarKey: "name",
          avatarSize: 56,
          titleKey: "name",
          minHeight: "72px",
        },
        fields: [
          {
            id: "location",
            dataKey: "address",
            icon: "LocationOn",
            iconSize: 18,
            fontSize: "0.85rem",
            alignItems: "flex-start",
            minHeight: "38px",
            clamp: 2,
            prefix: "Location:",
          },
          {
            id: "product",
            dataKey: "loanType",
            icon: "AccountBalance",
            iconSize: 18,
            fontSize: "0.85rem",
            minHeight: "24px",
            prefix: "Product:",
            fontWeight: 500,
          },
          {
            id: "loanAmount",
            dataKey: "amount",
            icon: "CurrencyRupee",
            iconSize: 18,
            fontSize: "0.85rem",
            fontWeight: 600,
            textColor: "success.main",
            minHeight: "24px",
            prefix: "Loan Amount:",
          },
        ],
      },
    },

    {
      id: "lead_details_dialog",
      type: "component",
      componentType: "dialog",
      title: "Lead Details",
      subtitle: "View and edit lead information",
      icon: "person",
      config: {
        maxWidth: "md",
        showAvatar: true,
        avatarKey: "name",
        titleKey: "name",
        subtitle: "Customer Details",
        showEditButton: true,

        // Dialog can have form sections inside
        sections: [
          {
            id: "lead_info_form",
            type: "form", // Form-based section inside dialog
            title: "Lead Information",
            subtitle: "Complete lead details",
            icon: "person",
            fields: [
              {
                id: "name",
                type: "text",
                label: "Full Name",
                dataKey: "name",
                placeholder: "Enter full name",
                required: true,
                icon: "person",
                xs: 12,
                md: 6,
              },
              {
                id: "mobileNumber",
                type: "text",
                label: "Mobile Number",
                dataKey: "mobileNumber",
                placeholder: "Enter mobile number",
                required: true,
                icon: "phone",
                xs: 12,
                md: 6,
                validation: {
                  pattern: "^\\d{10}$",
                  message: "Mobile number must be exactly 10 digits",
                },
              },
              {
                id: "email",
                type: "email",
                label: "Email",
                dataKey: "email",
                placeholder: "Enter email address",
                required: true,
                icon: "email",
                xs: 12,
                md: 6,
                validation: {
                  pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
                  message: "Please enter a valid email address",
                },
              },
              {
                id: "address",
                type: "text",
                label: "Address",
                dataKey: "address",
                placeholder: "Enter address",
                icon: "home",
                xs: 12,
                md: 6,
              },
              {
                id: "requirement",
                type: "select",
                label: "Requirement",
                dataKey: "requirement",
                placeholder: "Select requirement",
                xs: 12,
                md: 6,
                options: [
                  { value: "Home Loan", label: "Home Loan" },
                  { value: "Personal Loan", label: "Personal Loan" },
                  { value: "Business Loan", label: "Business Loan" },
                  { value: "Auto Loan", label: "Auto Loan" },
                ],
              },
              {
                id: "amount",
                type: "text",
                label: "Amount",
                dataKey: "amount",
                placeholder: "Enter amount",
                xs: 12,
                md: 6,
              },
              {
                id: "loanType",
                type: "select",
                label: "Loan Type",
                dataKey: "loanType",
                placeholder: "Select loan type",
                xs: 12,
                md: 6,
                options: [
                  { value: "Home Loan", label: "Home Loan" },
                  { value: "Personal Loan", label: "Personal Loan" },
                  { value: "Business Loan", label: "Business Loan" },
                  { value: "Auto Loan", label: "Auto Loan" },
                ],
              },
              {
                id: "sourcedBy",
                type: "text",
                label: "Sourced By",
                dataKey: "sourcedBy",
                placeholder: "Enter source name",
                icon: "person",
                xs: 12,
                md: 6,
              },
              {
                id: "income",
                type: "text",
                label: "Annual Income",
                dataKey: "income",
                placeholder: "Enter annual income",
                xs: 12,
                md: 4,
              },
              {
                id: "creditScore",
                type: "number",
                label: "Credit Score",
                dataKey: "creditScore",
                placeholder: "Enter credit score",
                xs: 12,
                md: 4,
              },
              {
                id: "employmentStatus",
                type: "select",
                label: "Employment Status",
                dataKey: "employmentStatus",
                placeholder: "Select employment status",
                xs: 12,
                md: 4,
                options: [
                  { value: "Full-time", label: "Full-time" },
                  { value: "Part-time", label: "Part-time" },
                  { value: "Self-employed", label: "Self-employed" },
                  { value: "Unemployed", label: "Unemployed" },
                ],
              },
              {
                id: "notes",
                type: "text",
                label: "Notes",
                dataKey: "notes",
                placeholder: "Enter any additional notes",
                multiline: true,
                rows: 3,
                xs: 12,
              },
            ],
          },
        ],

        // Dialog actions
        actions: [
          {
            id: "accept",
            label: "Accept",
            action: "accept",
            variant: "contained",
            color: "success",
            showIf: "viewing",
          },
          {
            id: "reject",
            label: "Reject",
            action: "reject",
            variant: "contained",
            color: "error",
            showIf: "viewing",
          },

          {
            id: "review",
            label: "Review",
            action: "review",
            variant: "contained",
            color: "warning",
            showIf: "viewing",
          },
          {
            id: "assign_to_rm",
            label: "Assign to RM",
            action: "assign_to_rm",
            variant: "contained",
            color: "warning",
            showIf: "viewing",
          },
        ],
      },
    },
  ],

  // Data source
  data: [
    {
      id: 1,
      name: "Rohit Sharma",
      address: "B-302, Lakeview Residency, Powai, Mumbai - 400076",
      requirement: "Individual Loan",
      amount: "INR 75,00,000",
      sourcedBy: "Priya Nair",
      mobileNumber: "9876543210",
      email: "rohit.sharma@example.in",
      loanType: "Individual Loan",
      income: "INR 18,00,000",
      creditScore: 785,
      employmentStatus: "Full-time",
      notes: "Upgrading to a larger apartment near Powai Lake",
      disabled: false,
      assign_to_rm: true,
    },
    {
      id: 2,
      name: "Ananya Gupta",
      address: "12/4 MG Road, Indiranagar, Bengaluru - 560038",
      requirement: "Joint Liability Loan",
      amount: "INR 6,50,000",
      sourcedBy: "Rahul Verma",
      mobileNumber: "9988776655",
      email: "ananya.gupta@example.in",
      loanType: "Joint Liability Loan",
      income: "INR 9,20,000",
      creditScore: 732,
      employmentStatus: "Full-time",
      notes: "Funding higher studies for younger brother",
      disabled: false,
      assign_to_rm: false,
    },
    {
      id: 3,
      name: "Suresh Iyer",
      address: "Plot 18, Gopal Industrial Estate, Chennai - 600058",
      requirement: "Agri Loan",
      amount: "INR 1,85,00,000",
      sourcedBy: "Neha Kulkarni",
      mobileNumber: "9123456780",
      email: "suresh.iyer@example.in",
      loanType: "Agri Loan",
      income: "INR 45,00,000",
      creditScore: 768,
      employmentStatus: "Self-employed",
      notes: "Expanding textile manufacturing unit in Ambattur",
      disabled: false,
      assign_to_rm: true,
    },
    {
      id: 4,
      name: "Meera Reddy",
      address: "Villa 14, Road 92, Jubilee Hills, Hyderabad - 500033",
      requirement: "Car Loan",
      amount: "INR 28,00,000",
      sourcedBy: "Aditya Rao",
      mobileNumber: "9012345678",
      email: "meera.reddy@example.in",
      loanType: "Car Loan",
      income: "INR 16,50,000",
      creditScore: 710,
      employmentStatus: "Full-time",
      notes: "Leasing an electric SUV for corporate commute",
      disabled: true,
      assign_to_rm: false,
    },
    {
      id: 5,
      name: "Arjun Patel",
      address: "501, Riverfront Residency, Ashram Road, Ahmedabad - 380009",
      requirement: "Individual Loan",
      amount: "INR 55,00,000",
      sourcedBy: "Sonal Shah",
      mobileNumber: "9825076543",
      email: "arjun.patel@example.in",
      loanType: "Individual Loan",
      income: "INR 14,80,000",
      creditScore: 756,
      employmentStatus: "Full-time",
      notes: "First-time buyer eligible for PMAY subsidy",
      disabled: false,
      assign_to_rm: false,
    },
    {
      id: 6,
      name: "Lata Menon",
      address: "16 Residency Road, Panampilly Nagar, Kochi - 682011",
      requirement: "Individual Loan",
      amount: "INR 4,25,000",
      sourcedBy: "Vishal Pillai",
      mobileNumber: "9847001122",
      email: "lata.menon@example.in",
      loanType: "Individual Loan",
      income: "INR 7,40,000",
      creditScore: 705,
      employmentStatus: "Part-time",
      notes: "Planned cardiac procedure at Aster Medcity",
      disabled: true,
      assign_to_rm: true,
    },
    {
      id: 7,
      name: "Devanshi Mehta",
      address: "H-27, Malviya Nagar, Jaipur - 302017",
      requirement: "Joint Liability Loan",
      amount: "INR 32,00,000",
      sourcedBy: "Karan Batra",
      mobileNumber: "9799887766",
      email: "devanshi.mehta@example.in",
      loanType: "Joint Liability Loan",
      income: "INR 21,00,000",
      creditScore: 742,
      employmentStatus: "Self-employed",
      notes: "Setting up a boutique handicraft studio for exports",
      disabled: false,
      assign_to_rm: false,
    },
    {
      id: 8,
      name: "Farhan Khan",
      address: "Flat 8C, Park Circus, Kolkata - 700017",
      requirement: "Car Loan",
      amount: "INR 8,20,000",
      sourcedBy: "Sangeeta Bose",
      mobileNumber: "9830012345",
      email: "farhan.khan@example.in",
      loanType: "Car Loan",
      income: "INR 10,50,000",
      creditScore: 688,
      employmentStatus: "Full-time",
      notes: "Home renovation and modular kitchen upgrade",
      disabled: true,
      assign_to_rm: false,
    },
    {
      id: 9,
      name: "Neha Deshpande",
      address: "3F, Baner Pashan Link Road, Pune - 411021",
      requirement: "Agri Loan",
      amount: "INR 48,00,000",
      sourcedBy: "Mahesh Patil",
      mobileNumber: "9090909090",
      email: "neha.deshpande@example.in",
      loanType: "Agri Loan",
      income: "INR 13,20,000",
      creditScore: 752,
      employmentStatus: "Full-time",
      notes: "Purchasing 2 BHK close to Hinjewadi IT park",
      disabled: false,
      assign_to_rm: true,
    },
    {
      id: 10,
      name: "Gaganpreet Singh",
      address: "H.No. 212, Sector 21, Chandigarh - 160022",
      requirement: "Joint Liability Loan",
      amount: "INR 65,00,000",
      sourcedBy: "Harleen Kaur",
      mobileNumber: "9878001234",
      email: "gaganpreet.singh@example.in",
      loanType: "Joint Liability Loan",
      income: "INR 27,50,000",
      creditScore: 739,
      employmentStatus: "Self-employed",
      notes: "Expanding refrigerated transport fleet for pharma",
      disabled: false,
      assign_to_rm: false,
    },
    {
      id: 11,
      name: "Aahana Mukherjee",
      address: "Block D, 18/2 Salt Lake, Kolkata - 700091",
      requirement: "Individual Loan",
      amount: "INR 3,80,000",
      sourcedBy: "Debashish Sen",
      mobileNumber: "9903123456",
      email: "aahana.mukherjee@example.in",
      loanType: "Individual Loan",
      income: "INR 6,80,000",
      creditScore: 702,
      employmentStatus: "Full-time",
      notes: "Destination wedding planning expenses in Goa",
      disabled: true,
      assign_to_rm: true,
    },
  ],
};

// Example: Pure Form Schema (like HDFC)
export const HDFCCustomerOnboardingSchema = {
  title: "HDFC Agriculture Instant KCC",
  description: "Please fill in your details to complete the onboarding process",

  sections: [
    {
      id: "aadhaar_section",
      type: "form", // Form-based section
      title: "Aadhaar Verification",
      subtitle: "Verify your identity",
      icon: "fingerprint",
      fields: [
        {
          id: "aadhaar_number",
          type: "text",
          label: "Aadhaar Number",
          placeholder: "Enter your 12 digit Aadhaar number",
          required: true,
          icon: "fingerprint",
          validation: {
            pattern: "^\\d{12}$",
            message: "Aadhaar number must be exactly 12 digits",
          },
        },
        {
          id: "biometric_scan",
          type: "biometric",
          label: "Tap to scan",
          required: false,
        },
        {
          id: "kyc_consent",
          type: "checkbox",
          label:
            "I hereby state that I have no objection for HDFC Bank validating and fetching my e-KYC details from UIDAI through the HDFC Bank e-KYC system and consent to provide my Aadhar number, biometric for Aadhar based KYC. Also I give consent to store my eKYC details for the purpose of KYC verification process with HDFC Bank.",
          required: true,
          validation: {
            message: "You must accept the terms to continue",
          },
        },
      ],
    },

    {
      id: "applicant_details",
      type: "form",
      title: "Applicant Details",
      subtitle: "Personal information",
      icon: "person",
      fields: [
        {
          id: "full_name",
          type: "text",
          label: "Full Name",
          placeholder: "Enter your full name",
          required: true,
          icon: "person",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            minLength: 3,
            message: "Full name must be at least 3 characters",
          },
        },
        {
          id: "date_of_birth",
          type: "date",
          label: "Date Of Birth",
          required: true,
          icon: "calendar",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            maxDate: "2006-01-01",
            message: "Date of birth must be before 2006",
          },
        },
        {
          id: "gender",
          type: "radio",
          label: "Gender",
          required: true,
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            message: "Please select a gender",
          },
          options: [
            { value: "male", label: "Male", icon: "male" },
            { value: "female", label: "Female", icon: "female" },
            { value: "transgender", label: "Transgender", icon: "transgender" },
          ],
        },
        {
          id: "care_of",
          type: "text",
          label: "C/O",
          placeholder: "Care of",
          required: false,
          icon: "home",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
        },
        {
          id: "father_name",
          type: "text",
          label: "Father Name",
          placeholder: "Enter father's name",
          required: true,
          icon: "person",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
        },
        {
          id: "mother_name",
          type: "text",
          label: "Mother Name",
          placeholder: "Enter mother's name",
          required: true,
          icon: "person",
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
        },
        {
          id: "pan_card_image",
          type: "image_capture",
          label: "PAN Card",
          placeholder: "Capture or upload your PAN card",
          required: true,
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            message: "PAN card image is required",
          },
        },
        {
          id: "customer_photo",
          type: "image_capture",
          label: "Customer Photo",
          placeholder: "Capture or upload your photo",
          required: true,
          enabledIf: {
            field: "kyc_consent",
            equals: true,
          },
          validation: {
            message: "Customer photo is required",
          },
        },
      ],
    },

    {
      id: "contact_details",
      type: "form",
      title: "Contact Information",
      subtitle: "How can we reach you",
      icon: "phone",
      fields: [
        {
          id: "mobile_number",
          type: "tel",
          label: "Mobile Number",
          placeholder: "Enter 10 digit mobile number",
          required: true,
          icon: "phone",
          validation: {
            pattern: "^\\d{10}$",
            message: "Mobile number must be exactly 10 digits",
          },
        },
        {
          id: "email",
          type: "email",
          label: "Email Address",
          placeholder: "Enter your email",
          required: true,
          icon: "email",
          validation: {
            pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
            message: "Please enter a valid email address",
          },
        },
        {
          id: "address",
          type: "text",
          label: "Address",
          placeholder: "Enter your complete address",
          required: true,
          multiline: true,
          rows: 3,
        },
      ],
    },
  ],

  submitButton: {
    label: "Submit Application",
    action: "submit",
  },
};
