export const productConfigStages = {
  title: "Product Configuration",
  description: "Configure loan products, schemes, and partner linkages",

  // Sidebar Configuration - Context & Calculations per Stage
  sidebarConfig: {
    width: 500,
    // Dynamic sections based on current stage
    stageContexts: {
      partner_registration: [
        {
          id: "registration_summary",
          type: "info",
          title: "Partner Information Summary",
          icon: "Business",
          fields: [
            { label: "Partner Name", key: "partner_name" },
            { label: "Partner Code", key: "partner_code" },
            { label: "Short Name", key: "partner_short_name" },
          ],
        },
        {
          id: "validation_status",
          type: "status",
          title: "Field Validation",
          items: [
            {
              label: "Partner Name",
              status: "pending",
              message: "Required field",
            },
            {
              label: "Partner Code",
              status: "pending",
              message: "Must be unique",
            },
            {
              label: "Address",
              status: "pending",
              message: "Complete address required",
            },
          ],
        },
      ],
      product_scheme_creation: [
        {
          id: "guidance",
          type: "guidance",
          title: "Configuration Guidance",
          icon: "Info",
          color: "info",
          content:
            "Define how the processing fee will be calculated. This is a critical step that impacts the net amount disbursed to the customer.",
        },
        {
          id: "lpf_ranges_summary",
          type: "calculation",
          title: "LPF Ranges Summary",
          icon: "ViewList",
          color: "success",
          calculations: [
            {
              label: "Total Ranges",
              formula: "1",
              format: "number",
              helpText: "Number of LPF ranges configured",
            },
            {
              label: "Fee Type",
              formula: "lpf_type",
              format: "text",
            },
            {
              label: "Min Loan Amount",
              formula: "min_loan_amount",
              format: "currency",
            },
            {
              label: "Max Loan Amount",
              formula: "max_loan_amount",
              format: "currency",
            },
          ],
        },

        {
          id: "fee_simulator",
          type: "simulator",
          title: "Live Rule Simulator",
          color: "success",
          description:
            "Test your fee rules as you build them. Enter a sample loan amount to see the calculated fee.",
          inputLabel: "Enter Loan Amount",
          inputPlaceholder: "e.g., 45000",
          calculations: [
            {
              label: "Processing Fee",
              formula: "calculateSlabFee",
              format: "currency",
            },
            {
              label: "GST (18%)",
              formula: "processing_fee * 0.18",
              format: "currency",
            },
            {
              label: "Total Fee",
              formula: "processing_fee + gst",
              format: "currency",
              highlight: true,
            },
          ],
          slabRules: {
            title: "Your Fee Slabs",
            emptyMessage: "Define fee slabs in the form to see them here",
            showLiveUpdate: true,
          },
        },
        {
          id: "interest_summary",
          type: "calculation",
          title: "Interest Rate Breakdown",
          icon: "Percent",
          color: "warning",
          calculations: [
            {
              label: "MCLR Rate",
              formula: "mclr",
              format: "percentage",
            },
            {
              label: "Spread",
              formula: "spread",
              format: "percentage",
            },
            {
              label: "Total Interest Rate",
              formula: "mclr + spread",
              format: "percentage",
              highlight: true,
              helpText: "Effective interest rate = MCLR + Spread",
            },
          ],
        },
        {
          id: "tenor_details",
          type: "info",
          title: "Loan Tenor & Insurance",
          icon: "Schedule",
          fields: [
            { label: "Loan Tenor", key: "loan_tenor", suffix: "months" },
            {
              label: "Insurance Premium",
              key: "insurance_premium",
              format: "currency",
            },
            { label: "Interest Type", key: "interest_rate_type" },
            { label: "Compounding", key: "periodicity_interest_compounding" },
          ],
        },
      ],
      scheme_linkage: [
        {
          id: "linkage_summary",
          type: "info",
          title: "Linkage Configuration",
          icon: "Link",
          fields: [
            { label: "Partner", key: "partner_name" },
            { label: "Scheme Code", key: "scheme_code" },
            { label: "Template Code", key: "template_code" },
          ],
        },
        {
          id: "linkage_validation",
          type: "status",
          title: "Linkage Validation",
          items: [
            { label: "Partner Exists", status: "checking" },
            { label: "Scheme Active", status: "checking" },
            { label: "Template Valid", status: "checking" },
          ],
        },
      ],
      sof: [
        {
          id: "sof_selection",
          type: "info",
          title: "SOF Selection Summary",
          icon: "Category",
          fields: [
            { label: "Sector", key: "sector" },
            { label: "Sub Sector", key: "sub_sector" },
            { label: "Activity", key: "activity_name" },
            { label: "State", key: "state" },
            { label: "District", key: "district" },
          ],
        },
        {
          id: "sof_value",
          type: "calculation",
          title: "SOF Value",
          icon: "AttachMoney",
          color: "success",
          calculations: [
            {
              label: "Selected SOF Value",
              formula: "sof_value",
              format: "currency",
              highlight: true,
              helpText: "Standard of Finance for selected activity",
            },
            {
              label: "Crop Name",
              formula: "crop_name",
              format: "text",
            },
          ],
        },
      ],
      bank_master: [
        {
          id: "bank_details",
          type: "info",
          title: "Bank Branch Details",
          icon: "AccountBalance",
          fields: [
            { label: "Country", key: "country" },
            { label: "State", key: "state" },
            { label: "City", key: "city" },
            { label: "SOL ID", key: "sol_id" },
          ],
        },
      ],
      other_information: [
        {
          id: "applicant_profile",
          type: "info",
          title: "Applicant Profile Summary",
          icon: "Person",
          fields: [
            { label: "Marital Status", key: "marital_status" },
            { label: "Education", key: "educational_qualification" },
            { label: "Profession", key: "profession" },
            {
              label: "Annual Income",
              key: "annual_net_income",
              format: "currency",
            },
            { label: "Category", key: "belongs_to" },
          ],
        },
        {
          id: "income_validation",
          type: "status",
          title: "Profile Validation",
          items: [
            {
              label: "Income Declared",
              status: "pending",
              message: "Annual income must be entered",
            },
            {
              label: "Education Verified",
              status: "pending",
              message: "Educational qualification required",
            },
            {
              label: "Profile Complete",
              status: "pending",
              message: "All mandatory fields must be filled",
            },
          ],
        },
      ],
      loan_document: [
        {
          id: "security_calculation",
          type: "calculation",
          title: "Security & Loan Amount",
          icon: "Security",
          color: "info",
          calculations: [
            {
              label: "Security Value",
              formula: "security_value",
              format: "currency",
              helpText: "Auto-populated from Eligible Loan Amount",
              highlight: true,
            },
            {
              label: "Distance from Branch",
              formula: "distance_from_branch",
              format: "number",
              suffix: "km",
            },
          ],
        },
        {
          id: "loan_questions_list",
          type: "info",
          title: "Loan Document Questions",
          icon: "Assignment",
          color: "success",
          questions: [
            {
              question: "Security Value",
              type: "Auto Fetched (Numeric)",
              required: true,
              note: "Auto-populated from Crop Details",
            },
            {
              question: "Distance from Bank Branch (kms)",
              type: "Numeric (Decimal)",
              required: false,
            },
            {
              question: "Applicant involved in farming activities",
              type: "Yes/No",
              required: false,
            },
            {
              question: "Source of irrigation, electricity facility available?",
              type: "Yes/No",
              required: false,
            },
            {
              question: "Agri land holding proof submitted?",
              type: "Yes/No",
              required: false,
            },
            {
              question: "Applicant and family actively involved in activity?",
              type: "Yes/No",
              required: false,
            },
            {
              question: "Experience in dairy farming activity",
              type: "Numeric (Decimal)",
              required: true,
            },
            {
              question: "Agri produce market nearby (Kms)",
              type: "Numeric (Decimal)",
              required: false,
            },
            {
              question: "Applicant and family involved in farming?",
              type: "Yes/No",
              required: false,
            },
            {
              question: "Experience in farming activity (yrs)",
              type: "Numeric (Decimal)",
              required: false,
            },
            {
              question: "Able to carry out set forth activities?",
              type: "Yes/No",
              required: false,
            },
            {
              question: "Purchase of Cattle Feed",
              type: "Multiple Selection",
              required: true,
            },
            {
              question: "Water supply",
              type: "Multiple Selection",
              required: true,
            },
            {
              question: "Veterinary aid",
              type: "Multiple Selection",
              required: true,
            },
            {
              question: "Sale of main products / by products",
              type: "Multiple Selection",
              required: true,
            },
          ],
        },
        {
          id: "applicant_details",
          type: "info",
          title: "Applicant Profile",
          icon: "Person",
          fields: [
            {
              label: "Farming Experience",
              key: "applicant_experience",
              suffix: "years",
            },
            { label: "Active in Farming", key: "applicant_involved_farming" },
            {
              label: "Irrigation Available",
              key: "irrigation_electricity_available",
            },
            { label: "Land Proof Submitted", key: "agri_land_proof_submitted" },
          ],
        },
      ],
      income_statement: [
        {
          id: "income_summary",
          type: "calculation",
          title: "Income Statement Summary",
          icon: "Assessment",
          color: "success",
          calculations: [
            {
              label: "Year 1 Net Income",
              formula: "year1_net_income",
              format: "currency",
            },
            {
              label: "Year 2 Net Income",
              formula: "year2_net_income",
              format: "currency",
            },
            {
              label: "Average Annual Income",
              formula: "(year1_net_income + year2_net_income) / 2",
              format: "currency",
              highlight: true,
            },
          ],
        },
        {
          id: "animal_details",
          type: "info",
          title: "Livestock Details",
          icon: "Pets",
          fields: [
            { label: "Type of Animal", key: "type_of_animal" },
            { label: "Number of Units", key: "number_of_units" },
            { label: "Liters per Day", key: "liters_per_animal_day" },
            { label: "Milking Days", key: "milking_days" },
          ],
        },
      ],
    },
  },

  // Stage Queue Configuration
  queueConfig: {
    title: "Product Configuration Stages",
    subtitle: "configurations in progress",
    searchPlaceholder: "Search configurations...",
    itemDisplayFields: {
      primary: "loan_product_name",
      secondary: "scheme_code",
      avatar: "loan_product_name",
    },
    statusField: "stage_status",
    statusChipLabel: "In Progress",
    statusChipColor: "info",
  },

  // Stages Configuration
  stages: [
    // {
    //   id: "product_scheme_linkage",
    //   title: "Product Scheme Linkage",
    //   shortTitle: "Scheme Linkage",
    //   type: "form",
    //   allowComments: true,
    //   color: "#9c27b0",
    //   icon: "Link",
    //   chipLabel: "Linkage",
    //   chipColor: "secondary",
    //   fields: [
    //     {
    //       id: "partner_name_link",
    //       label: "Partner Name",
    //       type: "dropdown",
    //       required: true,
    //       columnSpan: "half",
    //       dataType: "Drop-down",
    //       hint: "From Partner Registration module",
    //       options: [], // Populated dynamically from partner registration
    //     },
    //     {
    //       id: "scheme_code_link",
    //       label: "Scheme Code",
    //       type: "dropdown",
    //       required: true,
    //       columnSpan: "half",
    //       dataType: "Drop-down",
    //       hint: "From Product Scheme Creation module",
    //       options: [], // Populated dynamically from scheme creation
    //     },
    //     {
    //       id: "template_code_cre",
    //       label: "Template Code (CRE)",
    //       type: "dropdown",
    //       required: true,
    //       columnSpan: "half",
    //       dataType: "Drop-down",
    //       options: ["SOF"],
    //     },
    //   ],
    // },
    {
      id: "product_scheme_creation",
      title: "Product Scheme Creation",
      shortTitle: "Product Scheme",
      type: "form",
      allowComments: true,
      color: "#2e7d32", // Green
      icon: "Inventory",
      chipLabel: "Product",
      chipColor: "success",
      fields: [
        {
          id: "loan_type",
          label: "Loan Type",
          columnSpan: "half",
          type: "dropdown",
          required: true,
          dataType: "Drop-down",
          options: ["Instant KCC", "Allied"],
        },
        {
          id: "scheme_code",
          label: "Scheme Code",
          type: "number",
          required: true,
          columnSpan: "half", // 2 columns
          placeholder: "77001",
          dataType: "Free Text (numeric)",
        },
        {
          id: "scheme_type",
          label: "Scheme Type",
          type: "text",
          required: true,
          columnSpan: "half",
          placeholder: "FKCC NST- YEARLY",
          dataType: "Free Text",
          hint: "Should accept special characters",
        },
        {
          id: "state",
          label: "State",
          type: "dropdown",
          required: true,
          columnSpan: "full",
          dataType: "Drop-down",
          options: [
            "Andhra Pradesh",
            "Arunachal Pradesh",
            "Assam",
            "Bihar",
            "Chhattisgarh",
            "Goa",
            "Gujarat",
            "Haryana",
            "Himachal Pradesh",
            "Jharkhand",
            "Karnataka",
            "Kerala",
            "Madhya Pradesh",
            "Maharashtra",
            "Manipur",
            "Meghalaya",
            "Mizoram",
            "Nagaland",
            "Odisha",
            "Punjab",
            "Rajasthan",
            "Sikkim",
            "Tamil Nadu",
            "Telangana",
            "Tripura",
            "Uttar Pradesh",
            "Uttarakhand",
            "West Bengal",
          ],
        },
        {
          id: "min_loan_amount",
          label: "Min Loan Amount",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "1000",
          dataType: "Free Text (numeric)",
        },
        {
          id: "max_loan_amount",
          label: "Max Loan Amount",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "1600000",
          dataType: "Free Text (numeric)",
        },
        {
          id: "lpf_type",
          label: "Loan Processing Fee Type",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          options: ["Percentage", "Amount"],
          dataType: "Drop-down",
          hint: "Select fee calculation method",
        },
        // LPF Percentage Section
        {
          id: "lpf_percentage_section",
          label: "LPF as Percentage - Range",
          type: "section",
          repeatable: true,
          conditional: { field: "lpf_type", value: "Percentage" },
          fields: [
            {
              id: "lpf_perc_min_loan",
              label: "S/W Min Loan Amount",
              type: "number",
              placeholder: "25000",
            },
            {
              id: "lpf_perc_max_loan",
              label: "S/W Max Loan Amount",
              type: "number",
              placeholder: "50000",
            },
            {
              id: "lpf_percentage",
              label: "LPF %",
              type: "number",
              placeholder: "1",
            },
            {
              id: "lpf_min",
              label: "Minimum LPF",
              type: "number",
              placeholder: "1000",
            },
            {
              id: "lpf_gst_perc",
              label: "GST",
              type: "number",
              placeholder: "18",
            },
          ],
        },
        // LPF Amount Section
        {
          id: "lpf_amount_section",
          label: "LPF as Amount - Range",
          type: "section",
          repeatable: true,
          conditional: { field: "lpf_type", value: "Amount" },
          fields: [
            {
              id: "lpf_amt_min_loan",
              label: "S/W Min Loan Amount",
              type: "number",
              placeholder: "25000",
            },
            {
              id: "lpf_amt_max_loan",
              label: "S/W Max Loan Amount",
              type: "number",
              placeholder: "50000",
            },
            {
              id: "lpf_amount",
              label: "LPF Amount",
              type: "number",
              placeholder: "500",
            },
            {
              id: "lpf_gst_amt",
              label: "GST",
              type: "number",
              placeholder: "18",
            },
          ],
        },
        {
          id: "interest_rate_type",
          label: "Interest Rate Type",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["Fixed", "Floating"],
        },
        {
          id: "interest_rests",
          label: "Interest Rests",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["NA", "Yearly", "Half yearly"],
        },
        {
          id: "periodicity_reset_interest",
          label: "Periodicity for the Reset of Interest",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["NA", "Yearly", "Half yearly"],
        },
        {
          id: "rests_periodicity_compounding",
          label: "Rests/Periodicity of Interest Compounding",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["NA", "Yearly", "Half yearly"],
        },
        {
          id: "interest_rate",
          label: "Interest Rate",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "14",
          dataType: "Free Text (numeric)",
        },
        {
          id: "mclr",
          label: "MCLR",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "9",
          dataType: "Free Text (numeric)",
        },
        {
          id: "spread",
          label: "Spread",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "5",
          dataType: "Free Text (numeric)",
        },
        {
          id: "loan_tenor",
          label: "Loan Tenor",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["12", "24", "36"],
        },
        {
          id: "pais_premium",
          label: "PAIS Premium",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "12",
          dataType: "Free Text (numeric)",
        },

        // {
        //   id: "institution_type",
        //   label: "Institution Type",
        //   type: "dropdown",
        //   required: true,
        //   columnSpan: "half",
        //   dataType: "Drop-down",
        //   options: ["HDFC", "Partner(s)"],
        // },
      ],
    },
    {
      id: "partner_registration",
      title: "Partner Registration",
      shortTitle: "Partner Registration",
      type: "form",
      allowComments: true,
      color: "#1976d2", // Blue
      icon: "Business",
      chipLabel: "Registration",
      chipColor: "primary",
      fields: [
        {
          id: "partner_name",
          label: "Partner Name",
          type: "text",
          required: true,
          placeholder: "e.g., Agrosperity",
          dataType: "Free Text",
        },
        {
          id: "partner_short_name",
          label: "Partner Short Name",
          type: "text",
          required: true,
          placeholder: "e.g., AGROSP",
          dataType: "Free Text",
        },
        {
          id: "partner_address_line_1",
          label: "Partner Address Line 1",
          type: "text",
          required: true,
          dataType: "Free Text",
        },
        {
          id: "partner_address_line_2",
          label: "Partner Address Line 2",
          type: "text",
          required: true,
          dataType: "Free Text",
        },
        {
          id: "partner_code",
          label: "Partner Code",
          type: "text",
          required: true,
          dataType: "Free Text",
        },
      ],
    },

    {
      id: "sof",
      title: "SOF",
      shortTitle: "SOF",
      type: "form",
      allowComments: true,
      color: "#f57c00",
      icon: "Description",
      chipLabel: "SOF",
      chipColor: "warning",
      fields: [
        {
          id: "sector_code",
          label: "SECTOR CODE",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select sector code",
          options: ["101", "102", "103", "104"],
        },
        {
          id: "sector",
          label: "SECTOR",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select sector",
          options: [
            "FOOD & CASH CROPS",
            "FLOWERS & MEDICINAL PLANTS",
            "FRUITS, SPICES & PLANTATION CROPS",
            "GROWING OF FOOD & CASH CROPS-SHORT DURATION CROPS",
          ],
        },
        {
          id: "sub_sector_code",
          label: "Sub Sector Code",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select sub-sector code",
          options: [
            "SUCAN",
            "COTTO",
            "JUTE",
            "TOBAC",
            "OFACC",
            "FLOWE",
            "MEPLA",
            "TEA",
            "COFFE",
            "COCOA",
            "RUBBE",
            "FRUIT",
            "COCON",
            "EDNUT",
            "CARDA",
            "VANIL",
            "SPICE",
            "PADDY",
            "WHEAT",
            "OTCER",
            "PULSE",
          ],
        },
        {
          id: "sub_sector",
          label: "Sub Sector",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select sub-sector",
          options: [
            "SUGARCANE",
            "COTTON",
            "JUTE",
            "TOBACCO",
            "OTHER FOOD AND CASH CROPS",
            "FLOWERS",
            "MEDICINAL PLANTS",
            "TEA",
            "COFFEE",
            "COCOA",
            "RUBBER",
            "FRUITS",
            "COCONUT",
            "EDIBLE NUTS",
            "CARDAMOM",
            "VANILLA",
            "SPICES",
            "PADDY",
            "WHEAT",
            "OTHER CEREALS",
            "PULSES",
          ],
        },
        {
          id: "activity_code",
          label: "ACTIVITY_CODE",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select activity code",
          options: [
            "110401",
            "110501",
            "110601",
            "110701",
            "111901",
            "110901",
            "111101",
            "112101",
            "112301",
            "112302",
            "112401",
            "112501",
            "112601",
            "112602",
            "112701",
            "112702",
            "112703",
            "110101",
            "110102",
            "110103",
            "110201",
          ],
        },
        {
          id: "activity_name",
          label: "ACTIVITY_NAME",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select activity",
          options: [
            "SUGARCANE",
            "COTTON",
            "JUTE,MESTA,SUN HEMP",
            "TOBACCO",
            "POTATOES,JAMS,SWEET POTATOES",
            "FLOWERS",
            "MEDICINAL PLANTS",
            "TEA",
            "COFFEE",
            "COCOA",
            "RUBBER TREES",
            "FRUIT CROPS",
            "COCONUTS",
            "CASHEW,BADAM",
            "CARDAMOM",
            "VANILLA",
            "SPICE CROPS",
            "PADDY",
            "WHEAT",
            "OTHER CEREALS",
            "PULSES",
          ],
        },
        {
          id: "state_code",
          label: "State Code",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Tamil Nadu state code",
          options: ["33"],
        },
        {
          id: "state_sof",
          label: "State",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select state",
          options: ["Tamilnadu"],
        },
        {
          id: "district",
          label: "District",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select district",
          options: ["Tiruvallur", "Madurai", "Erode"],
        },
        {
          id: "district_code",
          label: "District Code",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select district code",
          options: ["589", "578", "573"],
        },
        {
          id: "crop_name",
          label: "Crop name",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select crop",
          options: [
            "SUGARCANE P (WD)",
            "SUGARCANE P (D)",
            "SUGARCANE R (WD)",
            "SUGARCANE R DRIP",
            "COTTON (Irrigated)",
            "COTTON (Rainfed)",
            "COTTON (Drip)",
            "JUTE",
            "MESTA",
            "SUNHEMP",
            "TOBACCO",
            "POTATO",
            "SWEET POTATO",
            "TAPIOCA",
            "TAPIOCA (Irrigated)",
            "JASMINE",
            "ROSE",
            "MARIGOLD",
            "CHRYSATHEMUM",
            "TUBEROSE",
            "CUT FLOWERS",
            "GERBERA",
            "MEDICINAL PLANTS",
            "TEA",
            "COFFEE",
            "COCOA",
            "RUBBER",
            "BANANA TISSUE CULTURE",
            "BANANA ORDINARY",
            "MANGO",
            "GRAPES",
            "LIME",
            "PAPAYA",
            "SAPOTA",
            "GUAVA",
            "AMLA",
            "ORANGE",
            "COCONUT",
            "CASHEW",
            "BADAM",
            "CARDAMOM",
            "VANILLA",
            "CLOVES",
            "TURMERIC",
            "CHILLI (Irrigated)",
            "PEPPER",
            "CINNAMON",
            "CUMIN",
            "CORIANDER",
            "PADDY (Irrigated)",
            "PADDY (Rainfed)",
            "PADDY (SRI)",
            "WHEAT",
            "RAGI (Irrigated)",
            "RAGI (Rainfed)",
            "PEARL MILLET (Irrigated)",
            "MAIZE (Irrigated)",
            "SORGHUM/JOWAR",
            "BARLEY",
            "Kodo Millet",
            "Little Millet",
            "Foxtail Millet",
            "RED GRAM (Irrigated)",
            "BLACK GRAM (Irrigated)",
            "GREEN GRAM (Irrigated)",
            "CHICK PEA (Irrigated)",
            "RED GRAM (Rainfed)",
            "BLACK GRAM (Rainfed)",
            "GREEN GRAM (Rainfed)",
            "CHICK PEA (Rainfed)",
          ],
        },
        {
          id: "sof_value",
          label: "SOF value",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Free Text (numeric)",
          hint: "Standard of Finance value (auto-calculated based on crop selection)",
          placeholder: "e.g., 48165",
          readOnly: true,
        },
        {
          id: "sof_excel_upload",
          label: "Bulk Upload SOF Data",
          type: "file",
          required: false,
          columnSpan: "full",
          accept: ".xlsx,.xls,.csv",
          placeholder: "Upload Excel File with SOF Data",
          hint: "Upload Excel containing: Sector Code, Sector, Sub Sector, Activity, State, District, Crop Name, SOF Value",
          dataType: "File Upload",
        },
      ],
    },
    {
      id: "bank_master",
      title: "Bank Master",
      shortTitle: "Bank Master",
      type: "form",
      allowComments: true,
      color: "#0288d1",
      icon: "AccountBalance",
      chipLabel: "Bank",
      chipColor: "info",
      fields: [
        {
          id: "country",
          label: "Country",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: ["India"],
        },
        {
          id: "state_bank",
          label: "State",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: [], // Indian states
        },
        {
          id: "city",
          label: "City",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: [], // Cities based on state
        },
        {
          id: "sol_id",
          label: "SOL ID",
          type: "text",
          required: true,
          columnSpan: "half",
          dataType: "Free Text",
        },
        {
          id: "bank_excel_upload",
          label: "Bulk Upload Bank Master Data",
          type: "file",
          required: false,
          columnSpan: "full",
          accept: ".xlsx,.xls,.csv",
          placeholder: "Upload Excel File with Bank Details",
          hint: "Upload Excel containing: Country, State, City, SOL ID columns",
          dataType: "File Upload",
        },
      ],
    },
    {
      id: "other_information",
      title: "Other Information",
      shortTitle: "Other Info",
      type: "form",
      allowComments: true,
      color: "#d32f2f",
      icon: "InfoOutlined",
      chipLabel: "Other Info",
      chipColor: "error",
      fields: [
        {
          id: "marital_status",
          label: "Marital Status",
          type: "dropdown",
          required: true,
          columnSpan: "full",
          dataType: "dropdown",
          options: ["Single", "Married", "Divorced", "Widowed"],
        },
        {
          id: "educational_qualification",
          label: "Educational Qualification",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: [
            "Below 10th",
            "10th Pass",
            "12th Pass",
            "Graduate",
            "Post Graduate",
            "Professional Degree",
          ],
        },
        {
          id: "annual_net_income",
          label: "Annual Net income",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Free Text (numeric)",
          placeholder: "Enter annual income",
        },
        {
          id: "profession",
          label: "Profession",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: [
            "Farmer",
            "Business",
            "Salaried",
            "Self Employed",
            "Daily Wage",
            "Others",
          ],
        },
        {
          id: "belongs_to",
          label: "Belongs to",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: ["General", "OBC", "SC", "ST", "Minority"],
        },
      ],
    },

    {
      id: "loan_document",
      title: "Loan Document",
      shortTitle: "Loan Document",
      type: "form",
      allowComments: true,
      color: "#00897b",
      icon: "FileCopy",
      chipLabel: "Document",
      chipColor: "success",
      fields: [
        {
          id: "security_value",
          label: "Security Value",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Auto Fetched (Numeric)",
          hint: "To be auto populated from Eligible Loan Amount calculated in the Crop Details session",
          readOnly: true,
        },
        {
          id: "distance_from_branch",
          label: "Distance from Bank Branch (in kms)",
          type: "decimal",
          required: false,
          columnSpan: "half",
          dataType: "Free text (numeric with decimals)",
        },
        {
          id: "loan_questionnaire",
          label: "Loan Document Questionnaire",
          type: "section",
          repeatable: true,
          fields: [
            {
              id: "question_text",
              label: "Question",
              type: "textarea",
              required: true,
              columnSpan: "full",
              placeholder:
                "Enter your question here (e.g., Applicant involved in farming activities?)",
              dataType: "Free Text",
            },
            {
              id: "answer_type",
              label: "Answer Type",
              type: "dropdown",
              required: true,
              columnSpan: "half",
              options: ["Yes/No", "Free Text", "Number", "Decimal"],
              dataType: "Dropdown",
            },
            {
              id: "is_required",
              label: "Required?",
              type: "dropdown",
              required: true,
              columnSpan: "half",
              options: ["Yes", "No"],
              dataType: "Dropdown",
            },
          ],
        },
      ],
    },
    {
      id: "income_expenditure",
      title: "Income & Expenditure",
      shortTitle: "Income & Expenditure",
      type: "form",
      allowComments: true,
      repeatable: true,
      color: "#7b1fa2",
      icon: "Assessment",
      chipLabel: "Income",
      chipColor: "secondary",
      fields: [
        {
          id: "farming_experience",
          label: "Applicant experience in farming activity (yrs)",
          type: "decimal",
          required: false,
          columnSpan: "half",
          dataType: "Free text (numeric with decimals)",
        },
        {
          id: "able_to_carry_out",
          label:
            "Whether the applicant able to carry out set forth activities?",
          type: "radio",
          required: false,
          dataType: "Radio Button",
          options: ["Yes", "No"],
        },
        {
          id: "arrangements",
          label: "Indicate the arrangements for",
          type: "subsection",
          fields: [
            {
              id: "cattle_feed_purchase",
              label: "Purchase of Cattle Feed",
              type: "multiselect",
              required: true,
              options: ["Self", "Cooperative", "Private Vendor", "Government"],
            },
            {
              id: "water_supply",
              label: "Water supply",
              type: "multiselect",
              required: true,
              options: ["Borewell", "Canal", "River", "Government Supply"],
            },
            {
              id: "veterinary_aid",
              label: "Veterinary aid",
              type: "multiselect",
              required: true,
              options: ["Private", "Government", "Cooperative"],
            },
            {
              id: "sale_products",
              label: "Sale of main products / by products",
              type: "multiselect",
              required: true,
              options: ["Direct Market", "Cooperative", "Private Buyers"],
            },
          ],
        },
        {
          id: "proof_activity",
          label: "Details of Proof of Activity submitted",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: [
            "Land Records",
            "Purchase Bills",
            "Sales Receipts",
            "Others",
          ],
        },
        {
          id: "ownership_nature",
          label: "Nature of Ownership",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["Owned", "Leased", "Mortgaged"],
        },
        {
          id: "agri_officer_comments",
          label: "Agri Officer Comments",
          type: "textarea",
          required: false,
          columnSpan: "full",
          dataType: "Free text (alpha numeric)",
        },
      ],
    },
    {
      id: "income_expenditure_statement",
      title: "Income Expenditure Statement",
      shortTitle: "Income Statement",
      type: "form",
      allowComments: true,
      repeatable: true,
      color: "#5e35b1",
      icon: "Assessment",
      chipLabel: "Financial",
      chipColor: "secondary", // Can add multiple years
      fields: [
        {
          id: "year",
          label: "Year",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Free text (numeric)",
          hint: "Previous 2 years data to be captured",
        },
        {
          id: "animal_type",
          label: "Type of animal",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop down",
          options: ["Cow", "Buffalo", "Goat", "Sheep", "Poultry"],
        },
        {
          id: "number_units",
          label: "Number of units",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Free text (numeric)",
        },
        {
          id: "liters_per_animal",
          label: "No. of liters per animal/day",
          type: "decimal",
          required: true,
          columnSpan: "half",
          dataType: "Free text (numeric)",
        },
        {
          id: "milking_days",
          label: "No. of milking days",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Free text (numeric)",
        },
        {
          id: "rate",
          label: "Rate",
          type: "decimal",
          required: true,
          columnSpan: "half",
          dataType: "Free text (numeric)",
          hint: "Rate per litre of milk to be entered",
        },
        {
          id: "income_byproduct",
          label: "Income (by product)",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Free text (numeric)",
          hint: "Numbers to be manually entered",
        },
        {
          id: "net_income_other",
          label: "Net income from other sources",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Free text (numeric)",
          hint: "Numbers to be manually entered",
        },
      ],
    },
  ],
};

export default productConfigStages;
