/**
 * Product Configuration Stages - Consolidated into 3 Categories
 * 1. Product Definition [Core] - prod name, min/max loan, int rate, tenure, scheme, process fee
 * 2. Eligibility Criteria - SOF (master), Purpose of loan/usage, Season, Income/Expense
 * 3. Verification & Operational Requirements - Bank master, Other info, Loan docs
 */

export const productConfigStages = {
  title: "Product Configuration",
  description:
    "Configure loan products, eligibility criteria, and operational requirements",

  // Sidebar Configuration - Context & Calculations per Stage
  sidebarConfig: {
    width: 500,
    stageContexts: {
      product_definition: [
        {
          id: "product_summary",
          type: "info",
          title: "Product Summary",
          icon: "Inventory",
          fields: [
            { label: "Product Name", key: "prod_name" },
            { label: "Scheme Code", key: "scheme_code" },
            { label: "Loan Range", key: "loan_range", format: "currency" },
          ],
        },
        // {
        //   id: "guidance",
        //   type: "guidance",
        //   title: "Configuration Guidance",
        //   icon: "Info",
        //   color: "info",
        //   content:
        //     "Define the core product parameters including loan amounts, interest rates, tenure, and processing fees. This forms the foundation of your loan product.",
        // },
        {
          id: "lpf_ranges_display",
          type: "lpf_ranges",
          title: "LPF Configuration",
          icon: "Receipt",
          description: "Loan Processing Fee ranges based on loan amount slabs",
          ranges: [
            {
              rangeNumber: 1,
              minLoanKey: "lpf_range1_min",
              maxLoanKey: "lpf_range1_max",
              percentageKey: "lpf_range1_percent",
              minFeeKey: "lpf_range1_min_fee",
              gstKey: "lpf_range1_gst",
            },
            {
              rangeNumber: 2,
              minLoanKey: "lpf_range2_min",
              maxLoanKey: "lpf_range2_max",
              percentageKey: "lpf_range2_percent",
              minFeeKey: "lpf_range2_min_fee",
              gstKey: "lpf_range2_gst",
            },
          ],
        },
        {
          id: "fee_simulator",
          type: "simulator",
          title: "Live Rule Simulator",
          color: "success",
          description:
            "Test your fee rules as you build them. Enter a sample loan amount to see the calculated fee.",
          inputLabel: "Enter Loan Amount",
          inputPlaceholder: "e.g., 45000",
          calculations: [
            {
              label: "Processing Fee",
              formula: "calculateSlabFee",
              format: "currency",
            },
            {
              label: "GST (18%)",
              formula: "processing_fee * 0.18",
              format: "currency",
            },
            {
              label: "Total Fee",
              formula: "processing_fee + gst",
              format: "currency",
              highlight: true,
            },
          ],
          slabRules: {
            title: "Your Fee Slabs",
            emptyMessage: "Define fee slabs in the form to see them here",
            showLiveUpdate: true,
          },
        },
        {
          id: "interest_summary",
          type: "calculation",
          title: "Interest Rate Breakdown",
          icon: "Percent",
          color: "warning",
          calculations: [
            { label: "MCLR Rate", formula: "mclr", format: "percentage" },
            { label: "Spread", formula: "spread", format: "percentage" },
            {
              label: "Total Interest Rate",
              formula: "mclr + spread",
              format: "percentage",
              highlight: true,
              helpText: "Effective interest rate = MCLR + Spread",
            },
          ],
        },
        {
          id: "tenor_details",
          type: "info",
          title: "Loan Tenor & Insurance",
          icon: "Schedule",
          fields: [
            { label: "Loan Tenor", key: "loan_tenor", suffix: "months" },
            {
              label: "Insurance Premium",
              key: "pais_premium",
              format: "currency",
            },
            { label: "Interest Type", key: "interest_rate_type" },
            { label: "Compounding", key: "rests_periodicity_compounding" },
          ],
        },
      ],
      eligibility_criteria: [
        {
          id: "sof_bulk_upload",
          type: "file_upload",
          title: "Bulk Upload SOF Data",
          icon: "CloudUpload",
          color: "success",
          accept: ".xlsx,.xls,.csv",
          description: "Upload Excel file to quickly populate SOF master data",
          columns: [
            "Sector Code",
            "Sector",
            "Sub Sector",
            "Activity",
            "State",
            "District",
            "Crop Name",
            "SOF Value",
          ],
          templateDownload: true,
          templateName: "SOF_Master_Template.xlsx",
        },
        {
          id: "sof_selection",
          type: "info",
          title: "SOF Selection Summary",
          icon: "Category",
          fields: [
            { label: "Sector", key: "sector" },
            { label: "Sub Sector", key: "sub_sector" },
            { label: "Activity", key: "activity_name" },
            { label: "State", key: "state_sof" },
            { label: "District", key: "district" },
          ],
        },
        {
          id: "sof_value",
          type: "calculation",
          title: "SOF Value",
          icon: "CurrencyRupee",
          color: "success",
          calculations: [
            {
              label: "Selected SOF Value",
              formula: "sof_value",
              format: "currency",
              highlight: true,
              helpText: "Standard of Finance for selected activity",
            },
            { label: "Crop Name", formula: "crop_name", format: "text" },
          ],
        },
        {
          id: "income_summary",
          type: "calculation",
          title: "Income Statement Summary",
          icon: "Assessment",
          color: "success",
          calculations: [
            {
              label: "Year 1 Net Income",
              formula: "year1_net_income",
              format: "currency",
            },
            {
              label: "Year 2 Net Income",
              formula: "year2_net_income",
              format: "currency",
            },
            {
              label: "Average Annual Income",
              formula: "(year1_net_income + year2_net_income) / 2",
              format: "currency",
              highlight: true,
            },
          ],
        },
        {
          id: "animal_details",
          type: "info",
          title: "Livestock Details",
          icon: "Pets",
          fields: [
            { label: "Type of Animal", key: "animal_type" },
            { label: "Number of Units", key: "number_units" },
            { label: "Liters per Day", key: "liters_per_animal" },
            { label: "Milking Days", key: "milking_days" },
          ],
        },
      ],
      verification_operational: [
        {
          id: "bank_bulk_upload",
          type: "file_upload",
          title: "Bulk Upload Bank Master",
          icon: "CloudUpload",
          color: "info",
          accept: ".xlsx,.xls,.csv",
          description: "Upload Excel file to quickly populate bank branch data",
          columns: ["Country", "State", "City", "SOL ID"],
          templateDownload: true,
          templateName: "Bank_Master_Template.xlsx",
        },
        {
          id: "bank_details",
          type: "info",
          title: "Bank Branch Details",
          icon: "AccountBalance",
          fields: [
            { label: "Country", key: "country" },
            { label: "State", key: "state_bank" },
            { label: "City", key: "city" },
            { label: "SOL ID", key: "sol_id" },
          ],
        },
        {
          id: "applicant_profile",
          type: "info",
          title: "Applicant Profile Summary",
          icon: "Person",
          fields: [
            { label: "Marital Status", key: "marital_status" },
            { label: "Education", key: "educational_qualification" },
            { label: "Profession", key: "profession" },
            {
              label: "Annual Income",
              key: "annual_net_income",
              format: "currency",
            },
            { label: "Category", key: "belongs_to" },
          ],
        },
        {
          id: "security_calculation",
          type: "calculation",
          title: "Security & Loan Amount",
          icon: "Security",
          color: "info",
          calculations: [
            {
              label: "Security Value",
              formula: "security_value",
              format: "currency",
              helpText: "Auto-populated from Eligible Loan Amount",
              highlight: true,
            },
            {
              label: "Distance from Branch",
              formula: "distance_from_branch",
              format: "number",
              suffix: "km",
            },
          ],
        },
        {
          id: "validation_status",
          type: "status",
          title: "Verification Status",
          items: [
            {
              label: "Bank Details",
              status: "pending",
              message: "Bank master configuration required",
            },
            {
              label: "Applicant Profile",
              status: "pending",
              message: "All mandatory fields must be filled",
            },
            {
              label: "Documents",
              status: "pending",
              message: "Loan document questionnaire required",
            },
          ],
        },
      ],
    },
  },

  // Stage Queue Configuration
  queueConfig: {
    title: "Product Configuration Stages",
    subtitle: "configurations in progress",
    searchPlaceholder: "Search configurations...",
    itemDisplayFields: {
      primary: "prod_name",
      secondary: "scheme_code",
      avatar: "prod_name",
    },
    statusField: "stage_status",
    statusChipLabel: "In Progress",
    statusChipColor: "info",
  },

  // ============================================
  // STAGES - Consolidated into 3 main categories
  // ============================================
  stages: [
    // ==========================================
    // STAGE 1: Product Definition [Core]
    // ==========================================
    {
      id: "product_definition",
      title: "Product Definition",
      shortTitle: "Product Definition",
      type: "form",
      allowComments: true,
      color: "#2e7d32",
      icon: "Inventory",
      chipLabel: "Core",
      chipColor: "success",
      description:
        "Define core Product parameters: name, loan limits, interest rates, tenure, scheme, and processing fees",
      sections: [
        {
          id: "basic_info",
          title: "Basic Information",
          icon: "Info",
          collapsible: true,
          defaultExpanded: true,
        },
        {
          id: "loan_limits",
          title: "Loan Limits",
          icon: "CurrencyRupee",
          collapsible: true,
          defaultExpanded: true,
        },
        {
          id: "interest_config",
          title: "Interest Configuration",
          icon: "TrendingUp",
          collapsible: true,
          defaultExpanded: true,
        },
        {
          id: "processing_fee",
          title: "Processing Fee",
          icon: "Receipt",
          collapsible: true,
          defaultExpanded: false,
        },
        {
          id: "partner_info",
          title: "Partner Information",
          icon: "Business",
          collapsible: true,
          defaultExpanded: false,
        },
      ],
      fields: [
        // === Basic Information Section ===
        {
          id: "prod_name",
          label: "Product Name",
          type: "text",
          required: true,
          columnSpan: "half",
          placeholder: "e.g., AGRI Loan, JLG Loan",
          dataType: "Free Text",
          section: "basic_info",
        },
        {
          id: "loan_type",
          label: "Loan Type",
          columnSpan: "half",
          type: "dropdown",
          required: true,
          placeholder: "Select Loan Type",
          dataType: "Dropdown",
          options: [
            "Instant KCC",
            "Allied",
            "Car Loan",
            "Bike Loan",
            "Home Loan",
            "Personal Loan",
          ],
          section: "basic_info",
        },
        {
          id: "scheme_code",
          label: "Scheme Code",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "77001",
          dataType: "Free Text (numeric)",
          section: "basic_info",
        },
        {
          id: "scheme_type",
          label: "Scheme Type",
          type: "text",
          required: true,
          columnSpan: "half",
          placeholder: "FKCC NST- YEARLY",
          dataType: "Free Text",
          hint: "Should accept special characters",
          section: "basic_info",
        },
        {
          id: "state",
          label: "State",
          type: "dropdown",
          required: true,
          columnSpan: "full",
          dataType: "Drop-down",
          options: [
            "Andhra Pradesh",
            "Arunachal Pradesh",
            "Assam",
            "Bihar",
            "Chhattisgarh",
            "Goa",
            "Gujarat",
            "Haryana",
            "Himachal Pradesh",
            "Jharkhand",
            "Karnataka",
            "Kerala",
            "Madhya Pradesh",
            "Maharashtra",
            "Manipur",
            "Meghalaya",
            "Mizoram",
            "Nagaland",
            "Odisha",
            "Punjab",
            "Rajasthan",
            "Sikkim",
            "Tamil Nadu",
            "Telangana",
            "Tripura",
            "Uttar Pradesh",
            "Uttarakhand",
            "West Bengal",
          ],
          section: "basic_info",
        },

        // === Loan Limits Section ===
        {
          id: "min_loan_amount",
          label: "Min Loan Amount",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "1000",
          dataType: "Free Text (numeric)",
          section: "loan_limits",
        },
        {
          id: "max_loan_amount",
          label: "Max Loan Amount",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "1600000",
          dataType: "Free Text (numeric)",
          section: "loan_limits",
        },

        // === Interest Configuration Section ===
        {
          id: "interest_rate_type",
          label: "Interest Rate Type",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["Fixed", "Floating"],
          section: "interest_config",
        },
        {
          id: "interest_rate",
          label: "Interest Rate (%)",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "14",
          dataType: "Free Text (numeric)",
          section: "interest_config",
        },
        {
          id: "mclr",
          label: "MCLR (%)",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "9",
          dataType: "Free Text (numeric)",
          section: "interest_config",
        },
        {
          id: "spread",
          label: "Spread (%)",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "5",
          dataType: "Free Text (numeric)",
          section: "interest_config",
        },
        {
          id: "interest_rests",
          label: "Interest Rests",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["NA", "Yearly", "Half yearly"],
          section: "interest_config",
        },
        {
          id: "periodicity_reset_interest",
          label: "Periodicity for Reset of Interest",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["NA", "Yearly", "Half yearly"],
          section: "interest_config",
        },
        {
          id: "rests_periodicity_compounding",
          label: "Periodicity of Interest Compounding",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["NA", "Yearly", "Half yearly"],
          section: "interest_config",
        },
        {
          id: "loan_tenor",
          label: "Loan Tenor (months)",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["12", "24", "36", "48", "60"],
          section: "interest_config",
        },
        {
          id: "pais_premium",
          label: "Insurance Premium",
          type: "number",
          required: true,
          columnSpan: "half",
          placeholder: "12",
          dataType: "Free Text (numeric)",
          section: "interest_config",
        },

        // === Processing Fee Section ===
        {
          id: "lpf_type",
          label: "Processing Fee Type",
          type: "dropdown",
          required: true,
          columnSpan: "full",
          options: ["Percentage", "Amount"],
          dataType: "Drop-down",
          hint: "Select fee calculation method",
          section: "processing_fee",
        },
        {
          id: "lpf_percentage_section",
          label: "LPF as Percentage - Range",
          type: "section",
          repeatable: true,
          conditional: { field: "lpf_type", value: "Percentage" },
          section: "processing_fee",
          fields: [
            {
              id: "lpf_perc_min_loan",
              label: "S/W Min Loan Amount",
              type: "number",
              placeholder: "25000",
            },
            {
              id: "lpf_perc_max_loan",
              label: "S/W Max Loan Amount",
              type: "number",
              placeholder: "50000",
            },
            {
              id: "lpf_percentage",
              label: "LPF %",
              type: "number",
              placeholder: "1",
            },
            {
              id: "lpf_min",
              label: "Minimum LPF",
              type: "number",
              placeholder: "1000",
            },
            {
              id: "lpf_gst_perc",
              label: "GST",
              type: "number",
              placeholder: "18",
            },
          ],
        },
        {
          id: "lpf_amount_section",
          label: "LPF as Amount - Range",
          type: "section",
          repeatable: true,
          conditional: { field: "lpf_type", value: "Amount" },
          section: "processing_fee",
          fields: [
            {
              id: "lpf_amt_min_loan",
              label: "S/W Min Loan Amount",
              type: "number",
              placeholder: "25000",
            },
            {
              id: "lpf_amt_max_loan",
              label: "S/W Max Loan Amount",
              type: "number",
              placeholder: "50000",
            },
            {
              id: "lpf_amount",
              label: "LPF Amount",
              type: "number",
              placeholder: "500",
            },
            {
              id: "lpf_gst_amt",
              label: "GST",
              type: "number",
              placeholder: "18",
            },
          ],
        },

        // === Partner Information Section ===
        {
          id: "partner_name",
          label: "Partner Name",
          type: "text",
          required: true,
          columnSpan: "half",
          placeholder: "e.g., Agrosperity",
          dataType: "Free Text",
          section: "partner_info",
        },
        {
          id: "partner_short_name",
          label: "Partner Short Name",
          type: "text",
          required: true,
          columnSpan: "half",
          placeholder: "e.g., AGROSP",
          dataType: "Free Text",
          section: "partner_info",
        },
        {
          id: "partner_address_line_1",
          label: "Partner Address Line 1",
          type: "text",
          required: true,
          columnSpan: "half",
          dataType: "Free Text",
          section: "partner_info",
        },
        {
          id: "partner_address_line_2",
          label: "Partner Address Line 2",
          type: "text",
          required: false,
          columnSpan: "half",
          dataType: "Free Text",
          section: "partner_info",
        },
        {
          id: "partner_code",
          label: "Partner Code",
          type: "text",
          required: true,
          columnSpan: "half",
          dataType: "Free Text",
          section: "partner_info",
        },
      ],
    },

    // ==========================================
    // STAGE 2: Eligibility Criteria
    // ==========================================
    {
      id: "eligibility_criteria",
      title: "Eligibility Criteria",
      shortTitle: "Eligibility Criteria",
      type: "form",
      allowComments: true,
      color: "#f57c00",
      icon: "Description",
      chipLabel: "Eligibility",
      chipColor: "warning",
      description:
        "Define SOF master, purpose of loan, season, and income/expense criteria",
      sections: [
        {
          id: "sof_master",
          title: "SOF (Master)",
          icon: "Category",
          collapsible: true,
          defaultExpanded: true,
        },
        {
          id: "purpose_usage",
          title: "Purpose of Loan / Usage",
          icon: "Assignment",
          collapsible: true,
          defaultExpanded: true,
        },
        {
          id: "season_info",
          title: "Season",
          icon: "WbSunny",
          collapsible: true,
          defaultExpanded: false,
        },
        {
          id: "income_expense",
          title: "Income / Expense",
          icon: "Assessment",
          collapsible: true,
          defaultExpanded: false,
        },
      ],
      fields: [
        // === SOF Master Section ===
        {
          id: "sector_code",
          label: "Sector Code",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select sector code",
          options: ["101", "102", "103", "104"],
          section: "sof_master",
        },
        {
          id: "sector",
          label: "Sector",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select sector",
          options: [
            "FOOD & CASH CROPS",
            "FLOWERS & MEDICINAL PLANTS",
            "FRUITS, SPICES & PLANTATION CROPS",
            "GROWING OF FOOD & CASH CROPS-SHORT DURATION CROPS",
          ],
          section: "sof_master",
        },
        {
          id: "sub_sector_code",
          label: "Sub Sector Code",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select sub-sector code",
          options: [
            "SUCAN",
            "COTTO",
            "JUTE",
            "TOBAC",
            "OFACC",
            "FLOWE",
            "MEPLA",
            "TEA",
            "COFFE",
            "COCOA",
            "RUBBE",
            "FRUIT",
            "COCON",
            "EDNUT",
            "CARDA",
            "VANIL",
            "SPICE",
            "PADDY",
            "WHEAT",
            "OTCER",
            "PULSE",
          ],
          section: "sof_master",
        },
        {
          id: "sub_sector",
          label: "Sub Sector",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select sub-sector",
          options: [
            "SUGARCANE",
            "COTTON",
            "JUTE",
            "TOBACCO",
            "OTHER FOOD AND CASH CROPS",
            "FLOWERS",
            "MEDICINAL PLANTS",
            "TEA",
            "COFFEE",
            "COCOA",
            "RUBBER",
            "FRUITS",
            "COCONUT",
            "EDIBLE NUTS",
            "CARDAMOM",
            "VANILLA",
            "SPICES",
            "PADDY",
            "WHEAT",
            "OTHER CEREALS",
            "PULSES",
          ],
          section: "sof_master",
        },
        {
          id: "activity_code",
          label: "Activity Code",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select activity code",
          options: [
            "110401",
            "110501",
            "110601",
            "110701",
            "111901",
            "110901",
            "111101",
            "112101",
            "112301",
            "112302",
            "112401",
            "112501",
            "112601",
            "112602",
            "112701",
            "112702",
            "112703",
            "110101",
            "110102",
            "110103",
            "110201",
          ],
          section: "sof_master",
        },
        {
          id: "activity_name",
          label: "Activity Name",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select activity",
          options: [
            "SUGARCANE",
            "COTTON",
            "JUTE,MESTA,SUN HEMP",
            "TOBACCO",
            "POTATOES,JAMS,SWEET POTATOES",
            "FLOWERS",
            "MEDICINAL PLANTS",
            "TEA",
            "COFFEE",
            "COCOA",
            "RUBBER TREES",
            "FRUIT CROPS",
            "COCONUTS",
            "CASHEW,BADAM",
            "CARDAMOM",
            "VANILLA",
            "SPICE CROPS",
            "PADDY",
            "WHEAT",
            "OTHER CEREALS",
            "PULSES",
          ],
          section: "sof_master",
        },
        {
          id: "state_code",
          label: "State Code",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select state code",
          options: ["33", "29", "27", "32", "28"],
          section: "sof_master",
        },
        {
          id: "state_sof",
          label: "State",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select state",
          options: [
            "Tamil Nadu",
            "Karnataka",
            "Maharashtra",
            "Kerala",
            "Andhra Pradesh",
          ],
          section: "sof_master",
        },
        {
          id: "district",
          label: "District",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select district",
          options: ["Tiruvallur", "Madurai", "Erode", "Chennai", "Coimbatore"],
          section: "sof_master",
        },
        {
          id: "district_code",
          label: "District Code",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select district code",
          options: ["589", "578", "573", "602", "641"],
          section: "sof_master",
        },
        {
          id: "crop_name",
          label: "Crop Name",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          hint: "Select crop",
          options: [
            "SUGARCANE P (WD)",
            "SUGARCANE P (D)",
            "SUGARCANE R (WD)",
            "SUGARCANE R DRIP",
            "COTTON (Irrigated)",
            "COTTON (Rainfed)",
            "COTTON (Drip)",
            "JUTE",
            "MESTA",
            "SUNHEMP",
            "TOBACCO",
            "POTATO",
            "SWEET POTATO",
            "TAPIOCA",
            "TAPIOCA (Irrigated)",
            "JASMINE",
            "ROSE",
            "MARIGOLD",
            "CHRYSATHEMUM",
            "TUBEROSE",
            "CUT FLOWERS",
            "GERBERA",
            "MEDICINAL PLANTS",
            "TEA",
            "COFFEE",
            "COCOA",
            "RUBBER",
            "BANANA TISSUE CULTURE",
            "BANANA ORDINARY",
            "MANGO",
            "GRAPES",
            "LIME",
            "PAPAYA",
            "SAPOTA",
            "GUAVA",
            "AMLA",
            "ORANGE",
            "COCONUT",
            "CASHEW",
            "BADAM",
            "CARDAMOM",
            "VANILLA",
            "CLOVES",
            "TURMERIC",
            "CHILLI (Irrigated)",
            "PEPPER",
            "CINNAMON",
            "CUMIN",
            "CORIANDER",
            "PADDY (Irrigated)",
            "PADDY (Rainfed)",
            "PADDY (SRI)",
            "WHEAT",
            "RAGI (Irrigated)",
            "RAGI (Rainfed)",
            "PEARL MILLET (Irrigated)",
            "MAIZE (Irrigated)",
            "SORGHUM/JOWAR",
            "BARLEY",
            "Kodo Millet",
            "Little Millet",
            "Foxtail Millet",
            "RED GRAM (Irrigated)",
            "BLACK GRAM (Irrigated)",
            "GREEN GRAM (Irrigated)",
            "CHICK PEA (Irrigated)",
            "RED GRAM (Rainfed)",
            "BLACK GRAM (Rainfed)",
            "GREEN GRAM (Rainfed)",
            "CHICK PEA (Rainfed)",
          ],
          section: "sof_master",
        },
        {
          id: "sof_value",
          label: "SOF Value",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Free Text (numeric)",
          hint: "Standard of Finance value (auto-calculated based on crop selection)",
          placeholder: "e.g., 48165",
          readOnly: true,
          section: "sof_master",
        },
        // === Purpose of Loan / Usage Section ===
        {
          id: "loan_purpose",
          label: "Purpose of Loan",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: [
            "Crop Production",
            "Farm Mechanization",
            "Land Development",
            "Irrigation",
            "Allied Activities",
            "Post Harvest",
            "Marketing",
          ],
          section: "purpose_usage",
        },
        {
          id: "loan_usage",
          label: "Loan Usage",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: ["Working Capital", "Term Loan", "Composite Loan"],
          section: "purpose_usage",
        },
        {
          id: "usage_description",
          label: "Usage Description",
          type: "textarea",
          required: false,
          columnSpan: "full",
          placeholder: "Describe the intended use of the loan",
          dataType: "Free Text",
          section: "purpose_usage",
        },

        // === Season Section ===
        {
          id: "season_type",
          label: "Season Type",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: ["Kharif", "Rabi", "Summer", "Perennial"],
          section: "season_info",
        },
        {
          id: "season_start_month",
          label: "Season Start Month",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          section: "season_info",
        },
        {
          id: "season_end_month",
          label: "Season End Month",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          section: "season_info",
        },

        // === Income / Expense Section ===
        {
          id: "farming_experience",
          label: "Applicant Experience in Farming (years)",
          type: "decimal",
          required: false,
          columnSpan: "half",
          dataType: "Free text (numeric with decimals)",
          section: "income_expense",
        },
        {
          id: "able_to_carry_out",
          label: "Whether applicant able to carry out set forth activities?",
          type: "radio",
          required: false,
          columnSpan: "half",
          dataType: "Radio Button",
          options: ["Yes", "No"],
          section: "income_expense",
        },
        {
          id: "arrangements",
          label: "Indicate the arrangements for",
          type: "subsection",
          section: "income_expense",
          fields: [
            {
              id: "cattle_feed_purchase",
              label: "Purchase of Cattle Feed",
              type: "dropdown",
              required: true,
              placeholder: "Select arrangement",
              options: ["Self", "Cooperative", "Private Vendor", "Government"],
            },
            {
              id: "water_supply",
              label: "Water supply",
              type: "dropdown",
              required: true,
              placeholder: "Select arrangement",
              options: ["Borewell", "Canal", "River", "Government Supply"],
            },
            {
              id: "veterinary_aid",
              label: "Veterinary aid",
              type: "dropdown",
              required: true,
              placeholder: "Select arrangement",
              options: ["Private", "Government", "Cooperative"],
            },
            {
              id: "sale_products",
              label: "Sale of main products / by products",
              type: "dropdown",
              required: true,
              placeholder: "Select arrangement",
              options: ["Direct Market", "Cooperative", "Private Buyers"],
            },
          ],
        },
        {
          id: "proof_activity",
          label: "Details of Proof of Activity submitted",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: [
            "Land Records",
            "Purchase Bills",
            "Sales Receipts",
            "Others",
          ],
          section: "income_expense",
        },
        {
          id: "ownership_nature",
          label: "Nature of Ownership",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Drop-down",
          options: ["Owned", "Leased", "Mortgaged"],
          section: "income_expense",
        },
        {
          id: "agri_officer_comments",
          label: "Agri Officer Comments",
          type: "textarea",
          required: false,
          columnSpan: "full",
          dataType: "Free text (alpha numeric)",
          section: "income_expense",
        },
        // Income Statement Fields
        {
          id: "income_statement_section",
          label: "Income Expenditure Statement",
          type: "section",
          repeatable: true,
          section: "income_expense",
          hint: "Previous 2 years data to be captured",
          fields: [
            {
              id: "year",
              label: "Year",
              type: "number",
              required: true,
              columnSpan: "half",
              dataType: "Free text (numeric)",
            },
            {
              id: "animal_type",
              label: "Type of Animal",
              type: "dropdown",
              required: true,
              columnSpan: "half",
              options: ["Cow", "Buffalo", "Goat", "Sheep", "Poultry"],
            },
            {
              id: "number_units",
              label: "Number of Units",
              type: "number",
              required: true,
              columnSpan: "half",
            },
            {
              id: "liters_per_animal",
              label: "No. of liters per animal/day",
              type: "decimal",
              required: true,
              columnSpan: "half",
            },
            {
              id: "milking_days",
              label: "No. of milking days",
              type: "number",
              required: true,
              columnSpan: "half",
            },
            {
              id: "rate",
              label: "Rate (per litre)",
              type: "decimal",
              required: true,
              columnSpan: "half",
            },
            {
              id: "income_byproduct",
              label: "Income (by product)",
              type: "number",
              required: true,
              columnSpan: "half",
            },
            {
              id: "net_income_other",
              label: "Net income from other sources",
              type: "number",
              required: true,
              columnSpan: "half",
            },
          ],
        },
      ],
    },

    // ==========================================
    // STAGE 3: Verification & Operational Requirements
    // ==========================================
    {
      id: "verification_operational",
      title: "Verification & Operational Requirements",
      shortTitle: "Verification & Operations",
      type: "form",
      allowComments: true,
      color: "#0288d1",
      icon: "AccountBalance",
      chipLabel: "Operations",
      chipColor: "info",
      description:
        "Configure bank master, applicant information, and loan documentation requirements",
      sections: [
        {
          id: "bank_master",
          title: "Bank Master",
          icon: "AccountBalance",
          collapsible: true,
          defaultExpanded: true,
        },
        {
          id: "other_info",
          title: "Other Information",
          icon: "InfoOutlined",
          collapsible: true,
          defaultExpanded: true,
        },
        {
          id: "loan_docs",
          title: "Loan Documents",
          icon: "FileCopy",
          collapsible: true,
          defaultExpanded: false,
        },
      ],
      fields: [
        // === Bank Master Section ===
        {
          id: "country",
          label: "Country",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: ["India"],
          section: "bank_master",
        },
        {
          id: "state_bank",
          label: "State",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: [
            "Andhra Pradesh",
            "Arunachal Pradesh",
            "Assam",
            "Bihar",
            "Chhattisgarh",
            "Goa",
            "Gujarat",
            "Haryana",
            "Himachal Pradesh",
            "Jharkhand",
            "Karnataka",
            "Kerala",
            "Madhya Pradesh",
            "Maharashtra",
            "Manipur",
            "Meghalaya",
            "Mizoram",
            "Nagaland",
            "Odisha",
            "Punjab",
            "Rajasthan",
            "Sikkim",
            "Tamil Nadu",
            "Telangana",
            "Tripura",
            "Uttar Pradesh",
            "Uttarakhand",
            "West Bengal",
          ],
          section: "bank_master",
        },
        {
          id: "city",
          label: "City",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: ["Jamnagar", "Bangalore"],
          hint: "Cities will be populated based on state selection",
          section: "bank_master",
        },
        {
          id: "sol_id",
          label: "SOL ID",
          type: "text",
          required: true,
          columnSpan: "half",
          dataType: "Free Text",
          section: "bank_master",
        },
        // === Other Information Section ===
        {
          id: "marital_status",
          label: "Marital Status",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "dropdown",
          options: ["Single", "Married", "Divorced", "Widowed"],
          section: "other_info",
        },
        {
          id: "educational_qualification",
          label: "Educational Qualification",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: [
            "Below 10th",
            "10th Pass",
            "12th Pass",
            "Graduate",
            "Post Graduate",
            "Professional Degree",
          ],
          section: "other_info",
        },
        {
          id: "annual_net_income",
          label: "Annual Net Income",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Free Text (numeric)",
          placeholder: "Enter annual income",
          section: "other_info",
        },
        {
          id: "profession",
          label: "Profession",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: [
            "Farmer",
            "Business",
            "Salaried",
            "Self Employed",
            "Daily Wage",
            "Others",
          ],
          section: "other_info",
        },
        {
          id: "belongs_to",
          label: "Belongs to (Category)",
          type: "dropdown",
          required: true,
          columnSpan: "half",
          dataType: "Dropdown",
          options: ["General", "OBC", "SC", "ST", "Minority"],
          section: "other_info",
        },

        // === Loan Documents Section ===
        {
          id: "security_value",
          label: "Security Value",
          type: "number",
          required: true,
          columnSpan: "half",
          dataType: "Auto Fetched (Numeric)",
          hint: "To be auto populated from Eligible Loan Amount calculated in the Crop Details session",
          //   readOnly: true,
          section: "loan_docs",
        },
        {
          id: "distance_from_branch",
          label: "Distance from Bank Branch (in kms)",
          type: "decimal",
          required: false,
          columnSpan: "half",
          dataType: "Free text (numeric with decimals)",
          section: "loan_docs",
        },
        {
          id: "loan_questionnaire",
          label: "Loan Document Questionnaire",
          type: "section",
          repeatable: true,
          section: "loan_docs",
          fields: [
            {
              id: "question_text",
              label: "Question",
              type: "textarea",
              required: true,
              columnSpan: "full",
              placeholder:
                "Enter your question here (e.g., Applicant involved in farming activities?)",
              dataType: "Free Text",
            },
            {
              id: "answer_type",
              label: "Answer Type",
              type: "dropdown",
              required: true,
              columnSpan: "half",
              options: [
                "Yes/No",
                "Free Text",
                "Number",
                "Decimal",
                "Multiple Selection",
              ],
              dataType: "Dropdown",
            },
            {
              id: "is_required",
              label: "Required?",
              type: "dropdown",
              required: true,
              columnSpan: "half",
              options: ["Yes", "No"],
              dataType: "Dropdown",
            },
          ],
        },
        // Pre-defined questions as reference
        {
          id: "predefined_questions_info",
          label: "Standard Questions Reference",
          type: "info",
          section: "loan_docs",
          content: [
            "Applicant involved in farming activities? (Yes/No)",
            "Source of irrigation, electricity facility available? (Yes/No)",
            "Agri land holding proof submitted? (Yes/No)",
            "Applicant and family actively involved in activity? (Yes/No)",
            "Experience in dairy farming activity (Numeric)",
            "Agri produce market nearby (Kms) (Numeric)",
            "Experience in farming activity (yrs) (Numeric)",
            "Able to carry out set forth activities? (Yes/No)",
            "Purchase of Cattle Feed (Multiple Selection)",
            "Water supply (Multiple Selection)",
            "Veterinary aid (Multiple Selection)",
            "Sale of main products / by products (Multiple Selection)",
          ],
        },
      ],
    },
  ],
};

export default productConfigStages;
