/**
 * Product Configurator Mock Data and Schema
 * Reusable configuration for product management
 */

export const productConfigSchema = {
  title: "Product Configurator",
  description: "Manage loan products, schemes, and partner linkages",

  // Layout Configuration
  layout: {
    containerAlignment: "flex-start",
    containerPadding: { xs: 1, sm: 2, md: 3, lg: 4 },
    gap: { xs: 1, sm: 2, md: 3 },
    cardGrid: {
      columns: { xs: 1, sm: 1, md: 2, lg: 2, xl: 3 },
      gap: 2,
      autoRows: "1fr",
    },
    breakpoints: {
      xs: 0,
      sm: 600,
      md: 960,
      lg: 1280,
      xl: 1920,
    },
  },

  // Right Sidebar Configuration
  sidebar: {
    width: {
      xs: "100%",
      sm: 440,
      md: 485,
      lg: 550,
      xl: 645,
    },
    alwaysOpen: true,
    position: "fixed",
    top: 64,
    right: 0,
    maxHeight: "calc(100vh - 64px)",

    // Control Panel for Products
    controlPanel: {
      padding: 2,
      filterLayout: "grid",
      filterColumns: { xs: 1, sm: 2, md: 2 },
      filterGap: 2,
      compactMode: { xs: true, sm: true, md: false },
    },

    tabs: [
      {
        id: "summary_panel",
        type: "control_panel",
        label: "Summary",
        icon: "Dashboard",
        badge: null,
        // Product-specific filter groups
        filterGroups: [
          {
            id: "loan_type_filter",
            label: "FILTER BY LOAN TYPE",
            filters: [
              {
                id: "all_products",
                label: "All Products",
                value: "all",
                count: 12,
                filterKey: null,
                color: "#1976d2",
              },
              {
                id: "agri_loans",
                label: "AGRI Loans",
                value: "agri",
                count: 3,
                filterKey: "loan_type",
                filterValue: "instant_kcc",
                color: "#2e7d32",
              },
              {
                id: "jlg_loans",
                label: "JLG Loans",
                value: "jlg",
                count: 2,
                filterKey: "loan_type",
                filterValue: "allied",
                color: "#9c27b0",
              },
              {
                id: "vehicle_loans",
                label: "Vehicle Loans",
                value: "vehicle",
                count: 4,
                filterKey: "loan_type",
                filterValue: ["car_loan", "bike_loan"],
                color: "#f57c00",
              },
              {
                id: "house_loans",
                label: "House Loans",
                value: "house",
                count: 3,
                filterKey: "loan_type",
                filterValue: "home_loan",
                color: "#d32f2f",
              },
            ],
          },
          {
            id: "product_status",
            label: "PRODUCT STATUS",
            filters: [
              {
                id: "all_status",
                label: "All",
                value: "all",
                count: 12,
                filterKey: null,
                color: "#757575",
              },
              {
                id: "active",
                label: "Active",
                value: "active",
                count: 10,
                filterKey: "status",
                filterValue: "active",
                color: "#2e7d32",
              },
              {
                id: "pending",
                label: "Pending Review",
                value: "pending",
                count: 2,
                filterKey: "status",
                filterValue: "pending",
                color: "#ed6c02",
              },
              {
                id: "inactive",
                label: "Inactive",
                value: "inactive",
                count: 0,
                filterKey: "status",
                filterValue: "inactive",
                color: "#d32f2f",
              },
            ],
          },
        ],
        // Product-specific alerts
        alerts: [
          {
            id: "pending_review",
            type: "warning",
            icon: "Warning",
            title: "Products Pending Review",
            message: "2 product schemes awaiting approval",
            severity: "warning",
            timestamp: "30m ago",
          },
          {
            id: "scheme_expiring",
            type: "info",
            icon: "Schedule",
            title: "Scheme Rate Update",
            message: "MCLR rates need to be updated for 3 schemes",
            severity: "info",
            timestamp: "2h ago",
          },
          {
            id: "high_interest",
            type: "error",
            icon: "TrendingUp",
            title: "Interest Rate Alert",
            message: "1 scheme has interest rate above market average",
            severity: "error",
            timestamp: "1d ago",
          },
        ],
        // Product-specific activity history
        activityHistory: [
          {
            id: "act_001",
            action: "created",
            title: "Created AGRI Loan Product",
            user: "Rajesh Kumar",
            timestamp: "2 hours ago",
            icon: "Add",
            color: "#2e7d32",
            details: "New AGRI loan product scheme added",
          },
          {
            id: "act_002",
            action: "updated",
            title: "Updated JLG Loan Scheme",
            user: "Nikhil Kamath",
            timestamp: "5 hours ago",
            icon: "Edit",
            color: "#1976d2",
            details: "Interest rate changed from 12.5% to 12%",
          },
          {
            id: "act_003",
            action: "approved",
            title: "Approved Car Loan Product",
            user: "Priya Sharma",
            timestamp: "1 day ago",
            icon: "CheckCircle",
            color: "#2e7d32",
            details: "Premium Auto Loan scheme approved",
          },
          {
            id: "act_004",
            action: "linked",
            title: "Linked Partner to Scheme",
            user: "Amit Verma",
            timestamp: "2 days ago",
            icon: "Link",
            color: "#9c27b0",
            details: "Anchor Corporate linked to 3 schemes",
          },
        ],
      },
      {
        id: "product_analytics",
        type: "analytics",
        label: "Analytics",
        icon: "BarChart",
        badge: null,
        stats: [
          {
            label: "Total Products",
            value: "12",
            trend: "+2",
            trendDirection: "up",
            icon: "Inventory",
          },
          {
            label: "Active Schemes",
            value: "10",
            trend: "+1",
            trendDirection: "up",
            icon: "CheckCircle",
          },
          {
            label: "Avg Interest Rate",
            value: "11.2%",
            trend: "-0.3%",
            trendDirection: "down",
            icon: "TrendingDown",
          },
          {
            label: "Partner Linkages",
            value: "6",
            trend: "0",
            trendDirection: "neutral",
            icon: "Handshake",
          },
        ],
      },
    ],
  },

  sections: [
    // Header Section
    {
      id: "header_section",
      type: "component",
      componentType: "header",
      props: {
        title: "Product Configurations",
        subtitle: "Manage loan products, schemes, and partner linkages",
        showCreateButton: true,
        createButtonLabel: "Create New Product",
        createButtonPosition: "top-right",
        searchPlaceholder: "Search products, schemes, partners...",
      },
    },

    // Filter Section with nested search
    {
      id: "filter_section",
      type: "component",
      componentType: "filter",
      config: {
        layout: "two-column",
        showDividers: true,
        sections: [
          {
            id: "search_section",
            type: "search",
            placeholder: "Search products, schemes, partners...",
            searchableFields: [
              "loan_product_name",
              "scheme_type",
              "partner_name",
              "created_by",
              "scheme_code",
            ],
          },
          {
            id: "stage_filters",
            type: "stage",
            label: "Product Type",
            filters: [
              {
                id: "all",
                label: "All Products",
                value: "all",
                filterKey: null,
              },
              {
                id: "instant_kcc",
                label: "Instant KCC",
                value: "instant_kcc",
                filterKey: "loan_type",
                filterValue: "instant_kcc",
              },
              {
                id: "allied",
                label: "Allied Loans",
                value: "allied",
                filterKey: "loan_type",
                filterValue: "allied",
              },
              {
                id: "vehicle",
                label: "Vehicle Loans",
                value: "vehicle",
                filterKey: "loan_type",
                filterValue: "car_loan",
              },
            ],
          },
        ],
      },
    },

    // Leads List Section (Cards)
    {
      id: "leads_list_section",
      type: "component",
      componentType: "cardList",
      config: {
        idKey: "id",
        cardStyle: "modern",
        header: {
          showAvatar: false,
          titleKey: "loan_product_name",
          subtitleKey: "product_scheme_label",
          minHeight: "60px",
        },
        fields: [
          {
            id: "scheme_type",
            dataKey: "scheme_type",
            icon: "Description",
            iconSize: 18,
            fontSize: "0.875rem",
            label: "SCHEME TYPE",
            fontWeight: 500,
          },
          {
            id: "partner_name",
            dataKey: "partner_name",
            icon: "Business",
            iconSize: 18,
            fontSize: "0.875rem",
            label: "PARTNER",
            fontWeight: 500,
          },
        ],
        metrics: [
          {
            id: "created_date",
            dataKey: "created_date",
            label: "CREATED DATE",
            icon: "CalendarToday",
            iconSize: 18,
            fontSize: "0.85rem",
            fontWeight: 600,
            color: "#1976d2",
            bgColor: "#1976d2",
            showLabel: true,
          },
          {
            id: "created_by",
            dataKey: "created_by",
            label: "CREATED BY",
            icon: "Person",
            iconSize: 18,
            fontSize: "0.85rem",
            fontWeight: 600,
            color: "#9c27b0",
            bgColor: "#9c27b0",
            showLabel: true,
          },
        ],
        badge: {
          dataKey: "status_badge",
          colorMap: {
            Active: "success",
            Pending: "warning",
            Inactive: "error",
          },
        },
        actionButton: {
          label: "Edit",
          variant: "contained",
          color: "primary",
        },
      },
    },

    // Lead Details Dialog (for product details view/edit)
    {
      id: "lead_details_dialog",
      type: "dialog",
      title: "Edit Product",
      maxWidth: "lg",
      fullWidth: true,
      sections: [
        {
          id: "product_edit_form",
          type: "form",
          fields: [
            {
              id: "loan_product_name",
              label: "Product Name",
              type: "select",
              required: true,
              options: [
                { value: "AGRI Loan", label: "AGRI Loan" },
                { value: "JLG Loan", label: "JLG Loan" },
                { value: "Car Loan", label: "Car Loan" },
                { value: "Bike Loan", label: "Bike Loan" },
                { value: "House Loan", label: "House Loan" },
              ],
            },
            {
              id: "scheme_type",
              label: "Scheme Type",
              type: "text",
              required: true,
              placeholder: "e.g., GFF Agri",
            },
            {
              id: "scheme_code",
              label: "Scheme Code",
              type: "text",
              required: true,
              placeholder: "e.g., 77001",
            },
            {
              id: "partner_name",
              label: "Partner Name",
              type: "select",
              required: true,
              options: [
                { value: "Anchor Corporate", label: "Anchor Corporate" },
                { value: "FarmTech Solutions", label: "FarmTech Solutions" },
                { value: "AutoFinance Ltd", label: "AutoFinance Ltd" },
              ],
            },
            {
              id: "loan_type",
              label: "Loan Type",
              type: "select",
              required: true,
              options: [
                { value: "instant_kcc", label: "Instant KCC" },
                { value: "allied", label: "Allied" },
                { value: "car_loan", label: "Car Loan" },
                { value: "bike_loan", label: "Bike Loan" },
                { value: "home_loan", label: "Home Loan" },
              ],
            },
            {
              id: "state",
              label: "State",
              type: "select",
              required: true,
              options: [
                { value: "Tamil Nadu", label: "Tamil Nadu" },
                { value: "Karnataka", label: "Karnataka" },
                { value: "Maharashtra", label: "Maharashtra" },
                { value: "Andhra Pradesh", label: "Andhra Pradesh" },
                { value: "Gujarat", label: "Gujarat" },
              ],
            },
            {
              id: "min_loan_amount",
              label: "Min Loan Amount",
              type: "number",
              required: true,
              placeholder: "e.g., 1000",
            },
            {
              id: "max_loan_amount",
              label: "Max Loan Amount",
              type: "number",
              required: true,
              placeholder: "e.g., 1600000",
            },
            {
              id: "interest_rate_value",
              label: "Interest Rate (%)",
              type: "number",
              required: true,
              placeholder: "e.g., 14",
              step: 0.1,
            },
            {
              id: "mclr",
              label: "MCLR (%)",
              type: "number",
              required: true,
              placeholder: "e.g., 9",
              step: 0.1,
            },
            {
              id: "spread",
              label: "Spread (%)",
              type: "number",
              required: true,
              placeholder: "e.g., 5",
              step: 0.1,
            },
            {
              id: "loan_tenor",
              label: "Loan Tenor (months)",
              type: "select",
              required: true,
              options: [
                { value: "12", label: "12 months" },
                { value: "24", label: "24 months" },
                { value: "36", label: "36 months" },
                { value: "60", label: "60 months" },
              ],
            },
            {
              id: "status",
              label: "Status",
              type: "select",
              required: true,
              options: [
                { value: "active", label: "Active" },
                { value: "pending", label: "Pending" },
                { value: "inactive", label: "Inactive" },
              ],
            },
          ],
        },
      ],
    },

    // Form Section
    {
      id: "form_section",
      componentType: "form",
      props: {
        sections: [
          // Partner Registration
          {
            id: "partner_registration",
            title: "Partner Registration",
            icon: "Business",
            fields: [
              {
                id: "partner_name",
                label: "Partner Name",
                type: "text",
                required: true,
                placeholder: "e.g., Agrosperity",
                validation: {
                  pattern: "^[a-zA-Z0-9\\s]+$",
                  message: "Only alphanumeric characters allowed",
                },
              },
              {
                id: "partner_short_name",
                label: "Partner Short Name",
                type: "text",
                required: true,
                placeholder: "e.g., AGROSP",
                maxLength: 10,
                validation: {
                  pattern: "^[A-Z0-9]+$",
                  message: "Only uppercase letters and numbers",
                },
              },
              {
                id: "partner_address_1",
                label: "Partner Address Line 1",
                type: "text",
                required: true,
                placeholder: "Building name, Street",
              },
              {
                id: "partner_address_2",
                label: "Partner Address Line 2",
                type: "text",
                required: true,
                placeholder: "City, Landmark",
              },
              {
                id: "partner_code",
                label: "Partner Code",
                type: "text",
                required: true,
                placeholder: "e.g., PART001",
              },
            ],
          },

          // Product Scheme Creation
          {
            id: "product_scheme_creation",
            title: "Product Scheme Creation",
            icon: "Assignment",
            fields: [
              {
                id: "loan_type",
                label: "Loan Type",
                type: "select",
                required: true,
                options: [
                  { value: "instant_kcc", label: "Instant KCC" },
                  { value: "allied", label: "Allied" },
                  { value: "car_loan", label: "Car Loan" },
                  { value: "bike_loan", label: "Bike Loan" },
                  { value: "home_loan", label: "Home Loan" },
                  { value: "personal_loan", label: "Personal Loan" },
                ],
              },
              {
                id: "scheme_code",
                label: "Scheme Code",
                type: "number",
                required: true,
                placeholder: "e.g., 77001",
              },
              {
                id: "scheme_type",
                label: "Scheme Type",
                type: "text",
                required: true,
                placeholder: "e.g., FKCC NST- YEARLY",
                hint: "Special characters allowed",
              },
              {
                id: "state",
                label: "State",
                type: "select",
                required: true,
                options: [
                  { value: "andhra_pradesh", label: "Andhra Pradesh" },
                  { value: "arunachal_pradesh", label: "Arunachal Pradesh" },
                  { value: "assam", label: "Assam" },
                  { value: "bihar", label: "Bihar" },
                  { value: "chhattisgarh", label: "Chhattisgarh" },
                  { value: "goa", label: "Goa" },
                  { value: "gujarat", label: "Gujarat" },
                  { value: "haryana", label: "Haryana" },
                  { value: "himachal_pradesh", label: "Himachal Pradesh" },
                  { value: "jharkhand", label: "Jharkhand" },
                  { value: "karnataka", label: "Karnataka" },
                  { value: "kerala", label: "Kerala" },
                  { value: "madhya_pradesh", label: "Madhya Pradesh" },
                  { value: "maharashtra", label: "Maharashtra" },
                  { value: "manipur", label: "Manipur" },
                  { value: "meghalaya", label: "Meghalaya" },
                  { value: "mizoram", label: "Mizoram" },
                  { value: "nagaland", label: "Nagaland" },
                  { value: "odisha", label: "Odisha" },
                  { value: "punjab", label: "Punjab" },
                  { value: "rajasthan", label: "Rajasthan" },
                  { value: "sikkim", label: "Sikkim" },
                  { value: "tamil_nadu", label: "Tamil Nadu" },
                  { value: "telangana", label: "Telangana" },
                  { value: "tripura", label: "Tripura" },
                  { value: "uttar_pradesh", label: "Uttar Pradesh" },
                  { value: "uttarakhand", label: "Uttarakhand" },
                  { value: "west_bengal", label: "West Bengal" },
                ],
              },
              {
                id: "min_loan_amount",
                label: "Min Loan Amount",
                type: "number",
                required: true,
                placeholder: "e.g., 1000",
              },
              {
                id: "max_loan_amount",
                label: "Max Loan Amount",
                type: "number",
                required: true,
                placeholder: "e.g., 1600000",
              },
            ],
          },

          // Loan Processing Fee (Percentage)
          {
            id: "lpf_percentage",
            title: "Loan Processing Fee (Percentage Based)",
            icon: "Percent",
            conditional: true,
            fields: [
              {
                id: "lpf_percentage_enabled",
                label: "Enable Percentage-based Processing Fee",
                type: "checkbox",
              },
              {
                id: "lpf_slabs",
                label: "Processing Fee Slabs",
                type: "slab_table",
                conditional: "lpf_percentage_enabled",
                columns: [
                  { id: "min_amount", label: "Min Amount", type: "number" },
                  { id: "max_amount", label: "Max Amount", type: "number" },
                  { id: "lpf_percent", label: "LPF %", type: "number" },
                  { id: "min_lpf", label: "Min LPF", type: "number" },
                  { id: "gst", label: "GST %", type: "number", default: 18 },
                ],
              },
            ],
          },

          // Loan Processing Fee (Amount)
          {
            id: "lpf_amount",
            title: "Loan Processing Fee (Fixed Amount)",
            icon: "AttachMoney",
            conditional: true,
            fields: [
              {
                id: "lpf_amount_enabled",
                label: "Enable Fixed Amount Processing Fee",
                type: "checkbox",
              },
              {
                id: "lpf_amount_slabs",
                label: "Processing Fee Slabs",
                type: "slab_table",
                conditional: "lpf_amount_enabled",
                columns: [
                  { id: "min_amount", label: "Min Amount", type: "number" },
                  { id: "max_amount", label: "Max Amount", type: "number" },
                  { id: "lpf_amount", label: "LPF Amount", type: "number" },
                  { id: "gst", label: "GST %", type: "number", default: 18 },
                ],
              },
            ],
          },

          // Interest Configuration
          {
            id: "interest_configuration",
            title: "Interest Configuration",
            icon: "TrendingUp",
            fields: [
              {
                id: "interest_rate_type",
                label: "Interest Rate Type",
                type: "select",
                required: true,
                options: [
                  { value: "fixed", label: "Fixed" },
                  { value: "floating", label: "Floating" },
                ],
              },
              // {
              //   id: "interest_rests",
              //   label: "Interest Rests",
              //   type: "select",
              //   required: true,
              //   options: [
              //     { value: "na", label: "NA" },
              //     { value: "yearly", label: "Yearly" },
              //     { value: "half_yearly", label: "Half Yearly" },
              //   ],
              // },
              {
                id: "periodicity_reset",
                label: "Periodicity for Reset of Interest",
                type: "select",
                required: true,
                options: [
                  { value: "na", label: "NA" },
                  { value: "yearly", label: "Yearly" },
                  { value: "half_yearly", label: "Half Yearly" },
                ],
              },
              {
                id: "rests_periodicity",
                label: "Rests/Periodicity of Interest Compounding",
                type: "select",
                required: true,
                options: [
                  { value: "na", label: "NA" },
                  { value: "yearly", label: "Yearly" },
                  { value: "half_yearly", label: "Half Yearly" },
                ],
              },
              {
                id: "interest_rate",
                label: "Interest Rate (%)",
                type: "number",
                required: true,
                placeholder: "e.g., 14",
                step: 0.01,
              },
              {
                id: "mclr",
                label: "MCLR (%)",
                type: "number",
                required: true,
                placeholder: "e.g., 9",
                step: 0.01,
              },
              {
                id: "spread",
                label: "Spread (%)",
                type: "number",
                required: true,
                placeholder: "e.g., 5",
                step: 0.01,
              },
              {
                id: "loan_tenor",
                label: "Loan Tenor (months)",
                type: "select",
                required: true,
                options: [
                  { value: "12", label: "12 months" },
                  { value: "24", label: "24 months" },
                  { value: "36", label: "36 months" },
                ],
              },
              {
                id: "insurance_premium",
                label: "Insurance Premium",
                type: "number",
                required: true,
                placeholder: "e.g., 12",
              },
            ],
          },

          // Institution Details
          {
            id: "institution_details",
            title: "Institution Details",
            icon: "AccountBalance",
            fields: [
              {
                id: "institution_type",
                label: "Institution Type",
                type: "select",
                required: true,
                options: [
                  { value: "federal_bank", label: "Federal Bank" },
                  { value: "partner", label: "Partner(s)" },
                ],
              },
            ],
          },

          // Product Scheme Linkage
          {
            id: "product_scheme_linkage",
            title: "Product Scheme Linkage",
            icon: "Link",
            fields: [
              {
                id: "linked_partner_name",
                label: "Partner Name",
                type: "select",
                required: true,
                options: [], // Will be populated from partner registration
                hint: "Select from registered partners",
              },
              {
                id: "linked_scheme_code",
                label: "Scheme Code",
                type: "select",
                required: true,
                options: [], // Will be populated from created schemes
                hint: "Select from created schemes",
              },
              {
                id: "template_code",
                label: "Template Code (CRE)",
                type: "select",
                required: true,
                options: [
                  { value: "cre_001", label: "CRE-001 - Standard KCC" },
                  { value: "cre_002", label: "CRE-002 - Allied Loan" },
                  { value: "cre_003", label: "CRE-003 - Vehicle Loan" },
                ],
              },
            ],
          },
        ],
      },
    },
  ],

  // Mock data for product configurations
  data: [
    {
      id: "prod_001",
      loan_product_name: "AGRI Loan",
      product_scheme_label: "PRODUCT SCHEME - FED",
      scheme_code: "77001",
      scheme_type: "GFF Agri",
      partner_name: "Anchor Corporate",
      partner_short_name: "ANCHOR",
      loan_type: "instant_kcc",
      state: "Tamil Nadu",
      loan_range: "₹1,000 - ₹16,00,000",
      min_loan_amount: 1000,
      max_loan_amount: 1600000,
      interest_rate: "14%",
      interest_rate_value: 14,
      mclr: 9,
      spread: 5,
      loan_tenor: "24",
      status: "active",
      status_badge: "Active",
      created_date: "15 Jan 2024",
      created_by: "Rajesh Kumar",
      last_updated: "2024-11-10",
      institution_type: "federal_bank",
    },
    {
      id: "prod_002",
      loan_product_name: "JLG Loan",
      product_scheme_label: "PRODUCT SCHEME - FED",
      scheme_code: "77002",
      scheme_type: "GFF JLG",
      partner_name: "Anchor Corporate",
      partner_short_name: "ANCHOR",
      loan_type: "allied",
      state: "Karnataka",
      loan_range: "₹5,000 - ₹10,00,000",
      min_loan_amount: 5000,
      max_loan_amount: 1000000,
      interest_rate: "12.5%",
      interest_rate_value: 12.5,
      mclr: 8.5,
      spread: 4,
      loan_tenor: "36",
      status: "active",
      status_badge: "Active",
      created_date: "01 Feb 2024",
      created_by: "Nikhil Kamath",
      last_updated: "2024-11-12",
      institution_type: "partner",
    },
    {
      id: "prod_003",
      loan_product_name: "Car Loan",
      product_scheme_label: "PRODUCT SCHEME - FED",
      scheme_code: "77003",
      scheme_type: "Premium Auto Loan",
      partner_name: "Anchor Corporate",
      partner_short_name: "ANCHOR",
      loan_type: "car_loan",
      state: "Maharashtra",
      loan_range: "₹2,00,000 - ₹50,00,000",
      min_loan_amount: 200000,
      max_loan_amount: 5000000,
      interest_rate: "8.5%",
      interest_rate_value: 8.5,
      mclr: 7,
      spread: 1.5,
      loan_tenor: "60",
      status: "active",
      status_badge: "Active",
      created_date: "10 Mar 2024",
      created_by: "Priya Sharma",
      last_updated: "2024-11-14",
      institution_type: "federal_bank",
    },
    {
      id: "prod_004",
      loan_product_name: "Bike Loan",
      product_scheme_label: "PRODUCT SCHEME - FED",
      scheme_code: "77004",
      scheme_type: "Two Wheeler Finance",
      partner_name: "Anchor Corporate",
      partner_short_name: "ANCHOR",
      loan_type: "bike_loan",
      state: "Tamil Nadu",
      loan_range: "₹50,000 - ₹3,00,000",
      min_loan_amount: 50000,
      max_loan_amount: 300000,
      interest_rate: "9.5%",
      interest_rate_value: 9.5,
      mclr: 8,
      spread: 1.5,
      loan_tenor: "36",
      status: "active",
      status_badge: "Active",
      created_date: "05 Apr 2024",
      created_by: "Amit Verma",
      last_updated: "2024-11-13",
      institution_type: "partner",
    },
    {
      id: "prod_005",
      loan_product_name: "AGRI Loan",
      product_scheme_label: "PRODUCT SCHEME - FED",
      scheme_code: "77005",
      scheme_type: "FKCC Seasonal",
      partner_name: "Anchor Corporate",
      partner_short_name: "ANCHOR",
      loan_type: "instant_kcc",
      state: "Andhra Pradesh",
      loan_range: "₹2,000 - ₹12,00,000",
      min_loan_amount: 2000,
      max_loan_amount: 1200000,
      interest_rate: "13.5%",
      interest_rate_value: 13.5,
      mclr: 9,
      spread: 4.5,
      loan_tenor: "12",
      status: "active",
      status_badge: "Active",
      created_date: "20 May 2024",
      created_by: "Kavita Reddy",
      last_updated: "2024-11-11",
      institution_type: "federal_bank",
    },
    {
      id: "prod_006",
      loan_product_name: "House Loan",
      product_scheme_label: "PRODUCT SCHEME - FED",
      scheme_code: "77006",
      scheme_type: "Affordable Housing",
      partner_name: "Anchor Corporate",
      partner_short_name: "ANCHOR",
      loan_type: "home_loan",
      state: "Gujarat",
      loan_range: "₹5,00,000 - ₹1,00,00,000",
      min_loan_amount: 500000,
      max_loan_amount: 10000000,
      interest_rate: "7.5%",
      interest_rate_value: 7.5,
      mclr: 6.5,
      spread: 1,
      loan_tenor: "240",
      status: "pending",
      status_badge: "Pending",
      created_date: "15 Jun 2024",
      created_by: "Sanjay Patel",
      last_updated: "2024-11-14",
      institution_type: "federal_bank",
    },
  ],
};

export default productConfigSchema;
